### PR TITLE
cli: generate commit template after selecting changes

### LINKED ISSUE #2439: `jj commit -i` commit message editor has inaccurate file listing
## Description

When I use `jj commit -i` and select changes from a subset of files, the commit message editor will say that the commit contains changes from all files. Note that `jj split` does not have this bug.

## Steps to Reproduce the Problem

1. `echo 1 > foo; echo 2 > bar`
1. `jj commit -i`
1. Select changes from `foo` only.
1. Observe the commit message editor (`.jjdescription` file).

## Expected Behavior

```
JJ: This commit contains the following changes:
JJ:     A foo
```

## Actual Behavior

```
JJ: This commit contains the following changes:
JJ:     A bar
JJ:     A foo
```

## Specifications

- Platform: Linux
- Version: 0.10.0

### PR DESCRIPTION
**Pull request by crackcomm**
Renamed `description_template_for_commit` to
`description_template_for_describe` since it's only used in `cmd_describe`.

Renamed `description_template_for_cmd_split` to
`description_template_for_commit` and modified to accomodate empty `intro` argument.

Fixes #2439.

Feel free to request any changes.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

File: cli/src/commands/commit.rs [hunk 1]
```diff
@@ -80,6 +78,16 @@ new working-copy commit.
...
+    let template = description_template_for_commit(
+        ui,
+        command.settings(),
+        tx.base_workspace_helper(),
+        "",
+        commit.description(),
+        &base_tree,
+        &middle_tree,
+    )?;
+
```
Comment (martinvonz) [inline cli/src/commands/commit.rs:90]: The code looks good, thanks! Could you also add a test? It looks like you could copy and/or modify one of these two: https://github.com/martinvonz/jj/blob/b11f7eee1b5b43f4589cb177d1bcbe4438ace17e/cli/tests/test_commit_command.rs#L36-L108

Comment (crackcomm) [reply cli/src/commands/commit.rs:90]: Sure, I have no idea how to make the interactive selection work though, should it be something like this:

```Rust
#[test]
fn test_commit_interactive() {
    let mut test_env = TestEnvironment::default();
    test_env.jj_cmd_ok(test_env.env_root(), &["init", "repo", "--git"]);
    let workspace_path = test_env.env_root().join("repo");

    std::fs::write(workspace_path.join("file1"), "foo\n").unwrap();
    std::fs::write(workspace_path.join("file2"), "bar\n").unwrap();
    let edit_script = test_env.set_up_fake_editor();
    std::fs::write(&edit_script, ["dump editor"].join("\0")).unwrap();

    let diff_editor = test_env.set_up_fake_diff_editor();
    std::fs::write(&diff_editor, "reset file2").unwrap();

    // Create a commit interactively and select only file1
    test_env.jj_cmd_ok(&workspace_path, &["commit", "-i"]);

    insta::assert_snapshot!(
        std::fs::read_to_string(test_env.env_root().join("editor")).unwrap(), @r###"

    JJ: This commit contains the following changes:
    JJ:     A file1

    JJ: Lines starting with "JJ: " (like this one) will be removed.
    "###);
}
```

**Comment by crackcomm** [comment]
I added a tests although I'm not sure the usage of fake diff editor is correct.

I repeatedly tried accepting the patch from `cargo insta review`

```
insta review finished
accepted:
  cli/tests/test_commit_command.rs:95 (commit_interactive)
```

but it still has some problems with whitespace

**Comment by yuja** [comment]
> but it still has some problems with whitespace

Insta doesn't handle leading/trailing whitespace very well. I think you can work around the problem by presetting some commit description by `jj describe -m`.

File: cli/src/description_util.rs [hunk 2]
```diff
@@ -107,6 +108,41 @@ pub fn description_template_for_commit(
...
+    template_chunks.push(if overall_commit_description.is_empty() {
+        settings.default_description()
+    } else {
+        overall_commit_description.to_owned()
+    });
+    if !diff_summary_bytes.is_empty() {
+        template_chunks.push("\n".to_owned());
+        template_chunks.push(diff_summary_to_description(&diff_summary_bytes));
+    }
+    Ok(template_chunks.join(""))
```
Comment (yuja) [inline cli/src/description_util.rs:143]: nit: `.concat()` also works.

Alternatively, the string can be built by using `+=` or `.push_str()`.

**Review by yuja — APPROVED** [review]
lgtm, thanks.

File: cli/src/description_util.rs (hunk 2 above)
Comment (crackcomm) [reply cli/src/description_util.rs]: Thanks, I changed it to `concat()`.

File: cli/src/commands/commit.rs (hunk 1 above)
Comment (martinvonz) [reply cli/src/commands/commit.rs:90]: Ah, you figured out how to do it :) I didn't notice comments below until now. Feel free to merge!
