### PR TITLE
git: cache the extra metadata table

### LINKED ISSUE #845: TableStore::get_head_tables is called a lot on repos with many commits
## Description

I noticed that, in a fresh `git clone https://github.com/NixOS/nixpkgs.git --branch master --single-branch` (then `jj init --git-repo=.`), that commands seem to take a long time; including `jj git push --dry-run`. I attached strace and noticed a lot of:

```
openat(AT_FDCWD, "/home/lukegb/Projects/nixpkgs-jj/./.jj/repo/store/extra/heads", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 6
newfstatat(6, "", {st_mode=S_IFDIR|0755, st_size=3, ...}, AT_EMPTY_PATH) = 0
brk(0x55ff74425000)                     = 0x55ff74425000
getdents64(6, 0x55ff743e4c40 /* 3 entries */, 131072) = 200
getdents64(6, 0x55ff743e4c40 /* 0 entries */, 131072) = 0
close(6)                                = 0
openat(AT_FDCWD, "/home/lukegb/Projects/nixpkgs-jj/./.jj/repo/store/extra/heads", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 6
newfstatat(6, "", {st_mode=S_IFDIR|0755, st_size=3, ...}, AT_EMPTY_PATH) = 0
getdents64(6, 0x55ff743f25a0 /* 3 entries */, 131072) = 200
getdents64(6, 0x55ff743f25a0 /* 0 entries */, 131072) = 0
close(6)                                = 0
openat(AT_FDCWD, "/home/lukegb/Projects/nixpkgs-jj/./.jj/repo/store/extra/heads", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 6
newfstatat(6, "", {st_mode=S_IFDIR|0755, st_size=3, ...}, AT_EMPTY_PATH) = 0
getdents64(6, 0x55ff74404a50 /* 3 entries */, 131072) = 200
getdents64(6, 0x55ff74404a50 /* 0 entries */, 131072) = 0
close(6)                                = 0
```

I did some digging and added a couple lines of code to print a backtrace inside TableStore::get_head_tables, which is I think the function that's doing this, and out of the gate got a lot of:

```
   0: jujutsu_lib::stacked_table::TableStore::get_head_tables
             at jj/lib/src/stacked_table.rs:456:25
   1: jujutsu_lib::stacked_table::TableStore::get_head
             at jj/lib/src/stacked_table.rs:468:26
   2: <jujutsu_lib::git_backend::GitBackend as jujutsu_lib::backend::Backend>::read_commit
             at jj/lib/src/git_backend.rs:393:21
   3: jujutsu_lib::store::Store::get_backend_commit
             at jj/lib/src/store.rs:78:22
   4: jujutsu_lib::store::Store::get_commit
             at jj/lib/src/store.rs:67:20
   5: jujutsu_lib::commit::Commit::parents::{{closure}}
             at jj/lib/src/commit.rs:86:23
   6: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/iter/adapters/map.rs:84:28
   7: core::iter::traits::iterator::Iterator::fold
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/iter/traits/iterator.rs:2414:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/iter/adapters/map.rs:124:9
   9: core::iter::traits::iterator::Iterator::for_each
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/iter/traits/iterator.rs:831:9
  10: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/vec/mod.rs:2880:17
  11: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/vec/spec_extend.rs:26:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/vec/spec_from_iter.rs:33:9
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/vec/mod.rs:2748:9
  15: core::iter::traits::iterator::Iterator::collect
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/iter/traits/iterator.rs:1836:9
  16: jujutsu_lib::commit::Commit::parents
             at jj/lib/src/commit.rs:83:9
  17: jujutsu_lib::repo::MutableRepo::add_head::{{closure}}
             at jj/lib/src/repo.rs:676:21
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/boxed.rs:2016:9
  19: jujutsu_lib::dag_walk::topo_order_reverse
             at jj/lib/src/dag_walk.rs:97:33
  20: jujutsu_lib::repo::MutableRepo::add_head
             at jj/lib/src/repo.rs:672:35
  21: jujutsu_lib::git::import_refs
             at jj/lib/src/git.rs:91:9
  22: jujutsu::cli_util::WorkspaceCommandHelper::import_git_refs_and_head
             at jj/src/cli_util.rs:413:9
  23: jujutsu::cli_util::WorkspaceCommandHelper::snapshot
             at jj/src/cli_util.rs:400:17
  24: jujutsu::cli_util::CommandHelper::workspace_helper
             at jj/src/cli_util.rs:312:9
  25: jujutsu::commands::cmd_git_push
             at jj/src/commands.rs:4326:33
  26: jujutsu::commands::cmd_git
             at jj/src/commands.rs:4658:47
  27: jujutsu::commands::run_command
             at jj/src/commands.rs:4709:36
  28: jj::run
             at jj/src/main.rs:41:5
  29: jj::main::{{closure}}
             at jj/src/main.rs:60:39
  30: core::result::Result<T,E>::and_then
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/result.rs:1372:22
  31: jj::main
             at jj/src/main.rs:60:18
[snip]
```

OK, that codepath only gets hit if `working_copy_shared_with_git` (inside `jujutsu::cli_util::WorkspaceCommandHelper::snapshot`); let's make that not true using `git config core.bare true`.

This pushes the problem down into the internals of the command I was running (again, `jj git push --dry-run`):

```
   0: jujutsu_lib::stacked_table::TableStore::get_head_tables
             at jj/lib/src/stacked_table.rs:456:25
   1: jujutsu_lib::stacked_table::TableStore::get_head
             at jj/lib/src/stacked_table.rs:468:26
   2: <jujutsu_lib::git_backend::GitBackend as jujutsu_lib::backend::Backend>::read_commit
             at jj/lib/src/git_backend.rs:393:21
   3: jujutsu_lib::store::Store::get_backend_commit
             at jj/lib/src/store.rs:78:22
   4: jujutsu_lib::store::Store::get_commit
             at jj/lib/src/store.rs:67:20
   5: jujutsu::commands::cmd_git_push
             at jj/src/commands.rs:4507:22
   6: jujutsu::commands::cmd_git
             at jj/src/commands.rs:4658:47
   7: jujutsu::commands::run_command
             at jj/src/commands.rs:4709:36
   8: jj::run
             at jj/src/main.rs:41:5
   9: jj::main::{{closure}}
             at jj/src/main.rs:60:39
  10: core::result::Result<T,E>::and_then
             at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/result.rs:1372:22
  11: jj::main
             at jj/src/main.rs:60:18
[...]
```

I think in general there might need to be some strategy for caching this so we don't repeatedly list the same directory over and over, but I don't know enough about jj's internals yet to be able to suggest anything (e.g. what would the lifetime of a cache like that look like, etc.)

## Steps to Reproduce the Problem

(This is a bit ugly, but effectively I have a very old `master` branch in my fork of the repo, since I never really look after it)

1. `git clone https://github.com/NixOS/nixpkgs.git nixpkgs-jj-repro --single-branch`
1. `cd nixpkgs-jj-repro`
1. `jj init --git-repo=.`
1. `jj co master`
1. `jj git remote rename origin old`
1. `jj git remote add origin https://github.com/lukegb/nixpkgs.git`
1. `jj branch c master -r old/master`
1. `jj git push --dry-run`

## Expected Behavior

`jj git push --dry-run` completes in a reasonable amount of time.

## Actual Behavior

It hangs, for a long time. `strace -p $(pidof jj)` reveals it's looking at `.jj/repo/store/extra/heads` a lot.

## Specifications

- Platform: x86_64-linux
- Version: `jj 0.5.1` (built from c52a14eac6532ba814c88f2c8c740415293bfb1a)

### PR DESCRIPTION
**Pull request by lukegb**
Performance on repositories with many commits is limited somewhat by repeatedly stating the tablestore directory to work out what the head is. By caching the table rather than looking it up from disk on every request, we can much more rapidly satisfy requests. 

This avoids the pathological case in #845 where jj operations take several minutes to complete.

This patch doesn't change the normal flow of the write path: that will still always call get_head() on the underlying TableStore, which will stat the directory before writing out changes. It will however empty the cache when the metadata has been written.

Fixes #845.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have added myself to the contributors in `CHANGELOG.md` (optional)

### CODE REVIEW

File: lib/src/git_backend.rs [hunk 1]
```diff
@@ -390,9 +392,17 @@ impl Backend for GitBackend {
             committer,
         };
 
-        let table = self.extra_metadata_store.get_head().map_err(|err| {
-            BackendError::Other(format!("Failed to read non-git metadata: {err}"))
-        })?;
+        let table = {
+            let mut locked_head = self.cached_extra_metadata.lock().unwrap();
+            match locked_head.take() {
```
Comment (martinvonz) [inline lib/src/git_backend.rs:397]: I'm confused about this `.take()`. It seems like it would remove the cached value, leaving a `None` in the mutex, so the next call would have to look it up again. `match locked_head.as_ref()` seems more appropriate.

**Review by martinvonz — COMMENTED** [review]
Thanks for fixing!

> * I have added myself to the contributors in `CHANGELOG.md` (optional)

I just wanted to make sure that you didn't miss this in the PR checklist.

File: lib/src/git_backend.rs (hunk 1 above)
Comment (lukegb) [reply lib/src/git_backend.rs]: Whoops; you're right: this should've been an `as_ref` with a `.clone` instead. Done.

**Comment by lukegb** [comment]
> > * I have added myself to the contributors in `CHANGELOG.md` (optional)
> 
> I just wanted to make sure that you didn't miss this in the PR checklist.

I saw this got removed from the checklist (hah, oops).

**Comment by martinvonz** [comment]
> > > * I have added myself to the contributors in `CHANGELOG.md` (optional)
> > 
> > 
> > I just wanted to make sure that you didn't miss this in the PR checklist.
> 
> I saw this got removed from the checklist (hah, oops).

We actually decided later that we're going to fill in that list just before the release instead because most people forgot to add themselves. So it doesn't matter whether you add yourself now, because I'll overwrite that list anyway :)

**Review by martinvonz — APPROVED** [review]

**Comment by martinvonz** [comment]
Reminder that you're free to merge this when you feel like it. It looks ready to me, but I'll let you decide when to merge it.
