### PR TITLE
Mark empty commits in jj log

### LINKED ISSUE #1028: Have `jj log` mark empty commits
I'd like `jj log` to mark which commits are empty. I have repeatedly been confused which of my `(no description set)` commits has files in it. Similarly, sometimes commits with description are unexpectedly empty.

Less importantly, I would put the empty marker next to the description since, in my mind, empty commits with a description are most likely to be a mistake a user might miss.

So, it could look like:

```
o 8bfb39ffaf7 user@example.com 2023-01-13 16:14 -08 btree HEAD@git a884a62710a
| (empty) BTree
:
```

or

```
@ b934eecf957 user@example.com 2023-01-13 16:14 -08 2cbc9988b68
| (empty) (no description set)
:
```

For the latter, the following is also an option, but it is less visible and seems a little more laborious to implement:

```
@ b934eecf957 user@example.com 2023-01-13 16:14 -08 2cbc9988b68
| (empty, no description set)
:
```

### PR DESCRIPTION
**Pull request by samueltardieu**
The tests are covered by existing ones.

I have chosen yellow as the "(empty)" marker color, maybe you would prefer another one.

Fix #1028.

# Checklist

If applicable:
- [X] I have updated `CHANGELOG.md`
- [X] I have updated the documentation (README.md, docs/, demos/)
- [X] I have added tests to cover my changes

### CODE REVIEW

File: src/templater.rs [hunk 1]
```diff
@@ -443,3 +444,14 @@ impl TemplateProperty<Signature, Timestamp> for SignatureTimestamp {
...
     }
 }
+
+pub struct EmptyProperty<'a> {
+    pub repo: RepoRef<'a>,
+}
+
+impl TemplateProperty<Commit, bool> for EmptyProperty<'_> {
+    fn extract(&self, context: &Commit) -> bool {
+        context.parents().len() == 1
```
Comment (dbarnett) [inline src/templater.rs:454]: Could use comments and/or intermediate variables here for readability. Looks like the first one is to ensure no merge and the 2nd is checking that the content hash is unchanged?

Comment (samueltardieu) [reply src/templater.rs:454]: That's right. I'll add a comment.

**Review by dbarnett — APPROVED** [review]
Great improvement! Thanks!

File: src/templater.rs [hunk 2]
```diff
@@ -443,3 +444,16 @@ impl TemplateProperty<Signature, Timestamp> for SignatureTimestamp {
...
+
+pub struct EmptyProperty<'a> {
+    pub repo: RepoRef<'a>,
+}
+
+impl TemplateProperty<Commit, bool> for EmptyProperty<'_> {
+    fn extract(&self, context: &Commit) -> bool {
+        // true iff the commit has exactly one parent (exclude root and merge commits)
+        // and the commit has not changed the tree content
+        context.parents().len() == 1
```
Comment (martinvonz) [inline src/templater.rs:456]: I think we should drop this check, so it works on merge commits too. That will make this `empty` true for most merge commits, which I understand can strange. However, it's more composable that; the condition to filter out merge commits could instead be done in the template (though we may need another template keyword for `merge` for that). We could consider doing that by default, but my inclination is that we should at least try start by just letting merge commits have the "(empty)" label to start with. That might help users get used to the idea that merge commits are typically empty.

We did the same thing for the `empty()` revset (which is just an alias for `~file(".")`) - that revset includes empty merges, so the user has to do `empty() - merges()` if they don't want merges.

I see you're already using `merge_commit_trees()` below, so just removing this condition should be enough.

File: src/config/colors.toml [hunk 3]
```diff
@@ -19,6 +19,7 @@
 "divergent" = "red"
 "divergent change_id"="red"
 "conflict" = "red"
+"empty" = "yellow"
```
Comment (martinvonz) [inline src/config/colors.toml:22]: Maybe we should add a `"working_copy empty" = "bright yellow"` for consistency, so everything on the working-copy commit lines is bright? That also reminds me of #528...

**Review by martinvonz — COMMENTED** [review]
Nice! Thanks for adding this.

File: src/templater.rs (hunk 2 above)
Comment (samueltardieu) [reply src/templater.rs:456]: Ok, I'll push a new version right away. Right now it will also consider the root commit empty, is that ok?

File: src/config/colors.toml (hunk 3 above)
Comment (samueltardieu) [reply src/config/colors.toml:22]: Sure!

File: src/templater.rs (hunk 2 above)
Comment (martinvonz) [reply src/templater.rs]: Yes, I think it makes sense that the root commit is considered empty. That matches what the `empty()` revset does.

**Review by martinvonz — APPROVED** [review]

File: src/templater.rs (hunk 2 above)
Comment (dbarnett) [reply src/templater.rs]: Would it make sense to specially flag if a merge is _not_ empty to make "evil merge" cases more obvious?

Comment (martinvonz) [reply src/templater.rs]: Yes, that probably makes sense since merge commits are typically empty. That's actually a good example of how it's better that this `empty` template doesn't treat merges specially, because now we can do something like `if(empty, if(!merge, "", "(NOT empty)"), if(merge, "", "(empty)"))` once we have a `merge` keyword.

**Comment by ilyagr** [comment]
That was quick. Thank you!

**Comment by ilyagr** [comment]
I'm really enjoying this. I tried out different colors, and using green here looks better to me than yellow. It nicely highlights the fact that the "empty" property is orthogonal to all the other properties of the commit. Any objections to changing it, @martinvonz , @samueltardieu , or anyone?

image

**Comment by samueltardieu** [comment]
No objection, I picked yellow for no other reason than "I have to pick one and it should be neutral".

**Comment by martinvonz** [comment]
Green sounds good to me too. You could change the color for email addresses too then, fixing #528

**Comment by martinvonz** [comment]
> Green sounds good to me too. You could change the color for email addresses too then, fixing #528

If you do, feel free to leave updating the screenshots in the README to me.

**Comment by ilyagr** [comment]
I think I'll just make the "working_copy email" normal yellow and bold, now that it's possible.

Here's what it looks like with `xterm`'s default theme:

Before:
image

After:
image

**Comment by ilyagr** [comment]
Also, depending on when and how many times you want to do it and what we decide, we could update the screenshots once we're highlighting prefixes by default.

**Comment by martinvonz** [comment]
Maybe we should just drop the bright colors for the working-copy commit completely, using only bold for it. Some terminals make bold text bold *and* bright (even when using ANSI code 38, unfortunately). iTerm2 does that by default, but maybe we can just tell users to turn that off?

**Comment by ilyagr** [comment]
I like it on my theme (see the screenshot of my dark theme above).

On the other hand, I just noticed that the `(no description set)` message is not visible on the light theme in the top commit. This might be a regression from the change in how we make things bold and bright.

So, I'm a bit attached to the bright colors, but if it keeps causing problems, we could certainly stop using them by default.

**Comment by martinvonz** [comment]
Alright, let's go with non-bright yellow then. I don't like the inconsistency of using bright colors for everything but email, but let's be pragmatic :)

**Comment by ilyagr** [comment]
Should I file a bug for the description message not being visible on the working copy commit on xterm's theme? Something must be hard-coding it to be white even on a bright theme.

**Comment by martinvonz** [comment]
> Should I file a bug for the description message not being visible on the working copy commit on xterm's theme? 

Please do. Thanks.

> Something must be hard-coding it to be white even on a bright theme.

https://github.com/martinvonz/jj/blob/aef080191726d3ffc823a98930e3a1bafb84a62a/src/config/colors.toml#L37.

**Comment by ilyagr** [comment]
Does your formatting magic PR support "bright normal"?
