### PR TITLE
Fix the ContentHash implementations for std::Option and MergedTreeId and RemoteRefState

### LINKED ISSUE #3051: The ContentHash implementation for std::Option is inconsistent with the documentation
The documentation for the `ContentHash` trait [states that](https://github.com/martinvonz/jj/blob/2e64bf83fd9b8abf4c9880482ea4ce19492f3139/lib/src/content_hash.rs#L10-L11):

> Enums should hash a 32-bit little-endian encoding of the ordinal number of the enum variant, then the variant's fields in lexical order.

This does not match the implementation for `std::Option`, which actually hashes the enum variant's ordinal number as `u8`, presumably with architecture specific endianness.

https://github.com/martinvonz/jj/blob/2e64bf83fd9b8abf4c9880482ea4ce19492f3139/lib/src/content_hash.rs#L76-L86

In `state.update(&[0])`, the `&[0]` is inferred as a `&[u8]` due to the function signature of `digest::Update.update)`.

image

I'm not sure what the implication is of changing the implementation after the fact. Presumably things will break. I think therefore we should update the documentation to say that the ordinal number should be hashed as a LE u8, and we should write the implementation as `state.update(&0.as_le_bytes())` to ensure portability.

### PR DESCRIPTION
**Pull request by emesterhazy**
The `ContentHash` documentation specifies that implementations for enums should hash the ordinal number of the variant contained in the enum as a 32-bit little-endian number and then hash the contents of the variant, if any.

The current implementations for `std::Option` and `MergedTreeId` are non-conformant since they hash the ordinal number as a u8 with platform specific endianness.

Fixes #3051

### CODE REVIEW

**Comment by emesterhazy** [comment]
Of course I forgot to update all of the tests which are now failing since we changed the hash function... I'll mail a new commit once I've worked through the dozens of failures.

**Comment by yuja** [comment]
We have one more enum: `RemoteRefState`. Well, I've basically copied it from the other enum impls, so most enums use `u8` ordinal (with the exception of `MergedTreeId` which uses ASCII b'0'.)

> I've worked through the dozens of failures.

Just fyi, what I usually do is:
```
cargo insta test --test-runner nextest
cargo insta review # or accept
```

**Comment by emesterhazy** [comment]
> We have one more enum: RemoteRefState. Well, I've basically copied it from the other enum impls, so most enums use u8 ordinal (with the exception of MergedTreeId which uses ASCII b'0'.)

I didn't see this before. Thanks for pointing it out. I'm not sure how to read the implementation for this one but it seems like it's non-conformant (even ignoring the u8) since I don't think Rust defines what tag values are used for the enum variants.

https://github.com/martinvonz/jj/blob/903f18acfd2365d4488eeea3425ab18615e23aa1/lib/src/op_store.rs#L207-L219

I'll fix it in the morning and push a new commit.

**Comment by yuja** [comment]
> I'm not sure how to read the implementation for this one but it seems like it's non-conformant (even ignoring the u8) since I don't think Rust defines what tag values are used for the enum variants.

It's `repr(u8)` enum, so the resulting value should be stable (across platforms). It doesn't conform to the documented spec, though.

File: lib/src/op_store.rs [hunk 1]
```diff
@@ -214,7 +214,10 @@ pub enum RemoteRefState {
 
 impl ContentHash for RemoteRefState {
     fn hash(&self, state: &mut impl digest::Update) {
-        (*self as u8).hash(state);
+        match self {
+            RemoteRefState::New => state.update(&0u32.to_le_bytes()),
+            RemoteRefState::Tracking => state.update(&1u32.to_le_bytes()),
+        }
```
Comment (Ralith) [inline lib/src/op_store.rs:220]: This would be simpler and more maintainable as `(*self as u32).to_le_bytes()).hash(state)`.

**Review by Ralith — APPROVED** [review]

**Comment by Ralith** [comment]
> u8 with platform specific endianness

For reference, note that `u8` has no endianness, as it's represented by a single byte. Endianness describes the layout of the bytes of an integer's representation, not individual bits.

> I don't think Rust defines what tag values are used for the enum variants.

Implicit discriminant values are specified [in the reference](https://doc.rust-lang.org/reference/items/enumerations.html#implicit-discriminants).

File: lib/src/op_store.rs (hunk 1 above)
Comment (emesterhazy) [reply lib/src/op_store.rs:220]: This actually fails because the 4 byte array representing the u32 gets hashed using this implementation:

https://github.com/martinvonz/jj/blob/903f18acfd2365d4488eeea3425ab18615e23aa1/lib/src/content_hash.rs#L55-L62

I'm going to leave it as-is for this reason. It's a bit of a moot point though w/r/t maintainability since the goal is to replace the hand coded version with the proc macro.

**Comment by emesterhazy** [comment]
All the tests are passing, but when I ran `jj` with the new binary on an existing repo, I got an error message:

```
➜  ~/o/g/m/jj ((500358b0)) jjx
Failed to load commit index file '3fdaff954f214d8d04fc21cd305961cc85cb4dcabb6c9d1c492f091b37c197afda06abf584900d24db8e24d98aeb7e516a6a
bba41a80fae16cb947e660bcc383': No such file or directory (os error 2). Reindexing...
```

After that it seemed to run fine. When I ran my 0.13.0 stable binary again on the same repo I got a different error:
```
➜  ~/o/g/m/jj ((500358b0)) jj
The index was corrupt (maybe the format has changed). Reindexing...
```

The difference in the message seems to be due to a change in the message itself in https://github.com/martinvonz/jj/commit/1f6d1de6, which is very recent and not included in my stable binary.

Again it seemed fine after re-indexing. I took a look at the code and I think everything will be ok, but would someone please confirm that this should be benign before I submit this change? @yuja I think you changed this index code most recently. What do you think?

We should probably mention in the patch notes for the next release that users will see this error after upgrading. FYI @martinvonz

**Comment by yuja** [comment]
> Failed to load commit index file '3fdaff954f214d8d04fc21cd305961cc85cb4dcabb6c9d1c492f091b37c197afda06abf584900d24db8e24d98aeb7e516a6a
> bba41a80fae16cb947e660bcc383': No such file or directory (os error 2). Reindexing...

It's not a problem of this PR. I'm doing some index format changes in this release cycle.

> Maybe we can change the migration code to just quietly rebuild the index

That's doable, but I'm not sure which is better. Reindexing can take few tens of seconds in mid-size repos.

File: lib/src/op_store.rs (hunk 1 above)
Comment (emesterhazy) [reply lib/src/op_store.rs:220]: Closing the loop, with `state.update((*self as u32).to_le_bytes());` and a new non-unit variant you get a non-primitive cast error.

```
error[E0605]: non-primitive cast: `op_store::RemoteRefState` as `u32`
   --> lib/src/op_store.rs:218:23
    |
218 |         state.update(&(*self as u32).to_le_bytes());
    |                       ^^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
    ```

With the explicit match statement you get an error saying that the match doesn't cover all cases.

I'll add ContentHash for u32 in a separate commit and use it to simplify the derive macro. No need IMO to rewrite the manual impls since they're going to be deleted.
