### PR TITLE
cli: remind the user to configure their name and email

### LINKED ISSUE #530: jj should walk users through setting their email/name
## Description

Right now searching for [jj "no email configured"](https://www.google.com/search?q=jj+%22no+email+configured%22) yields:

> It looks like there aren't many great matches for your search

Google is right

## Steps to Reproduce the Problem

1. install jj
2. clone a repo
3. use `jj log` 

## Expected Behavior

At some point in this process (possibly at clone, possibly at log), the user should be directed to how to set up their name/email

## Actual Behavior

`(no email configured)` as noted in #528 

## Specifications

- Platform:
- Version: 0.4.0

### PR DESCRIPTION
**Pull request by martinvonz**
This commit adds a reminder in `finish_transaction()` if the user hasn't configured their name and email. That means they'll get a reminder after most mutating commits, except for commands that only snapshot the working copy, and a few more cases.

Closes #530.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)

### CODE REVIEW

File: src/cli_util.rs [hunk 1]
```diff
@@ -797,6 +797,14 @@ impl WorkspaceCommandHelper {
             let git_repo = self.repo.store().git_repo().unwrap();
             git::export_refs(&self.repo, &git_repo)?;
         }
+        let settings = ui.settings();
+        if settings.user_name() == UserSettings::user_name_placeholder()
+            || settings.user_email() == UserSettings::user_email_placeholder()
+        {
+            ui.write_warn(r#"Name and email not configured. Add something like the following to $HOME/.jjconfig.toml:
+  user.name = "Some One"
+  user.email = "someone@example.com"#)?;
```
Comment (yuja) [inline src/cli_util.rs:806]: needs one more `"` to close email string.

**Review by yuja — APPROVED** [review]

File: src/cli_util.rs (hunk 1 above)
Comment (martinvonz) [reply src/cli_util.rs]: Good catch. Fixed.
