### PR TITLE
working_copy: implement symlinks on Windows with a helper function

### LINKED ISSUE #2: Add support for symlinks on Windows
We currently don't support symlinks on Windows (in fact, the project doesn't even build on Windows because of that). The advice I got from augie@google.com and former hg contributor "bmp" was (please correct me if I'm wrong):

* Prior to Windows 10: No symlink support
* Windows 10 without dev mode: No symlink support
* Windows 10 dev mode: use FFI to call CreateSymbolicLink
* Don't use the `symlink` creates, because it creates "junctions", which is not what we want.

Rust's standard library has `std::os::windows::fs::symlink_file` and  `std::os::windows::fs::symlink_dir`, which both seem to call `CreateSymbolicLinkW`, only with different flags. Perhaps we can always use the `symlink_file` version? It's still unclear to me what the effect would be if a "file symbolic link" points to a target that's actually a directory.

### PR DESCRIPTION
**Pull request by gulbanana**
Fixes #2

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [x] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by gulbanana** [comment]
Alright, we've got some test failures on windows-latest. They pass locally, but presumably the runner is not in developer mode and doesn't run as admin - Windows only supports symlinks if one of those things is true! I'll look into modifying the tests, which were previously #[cfg(unix)], so that they look for either success or a special "this Windows instance does not support this feature" error.

In order to achieve that I'll probably make the symlink abstraction the same on both windows and unix, instead of just having the same name. That way we can get better error messages at runtime when this failure occurs on unconfigured-for-symlinks machines.

**Comment by gulbanana** [comment]
The exact requirements for symlinks appear to be:
* winver 14972 or higher
* Developer Mode on
* pass flag SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE (`std` does this)

**Comment by gulbanana** [comment]
The test changes were more invasive than I hoped and so I've split them into an extra commit. This has some nasty nested error handling, and probably needs a restructure, but I don't know what patterns we prefer for this sort of thing - feedback appreciated!

File: lib/src/file_util.rs [hunk 1]
```diff
@@ -134,6 +146,39 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+    original: P,
+    link: Q,
+) -> Result<(), SymlinkError> {
+    const ERROR_PRIVILEGE_NOT_HELD: i32 = 1314;
+
+    if Path::is_dir(original.as_ref()) {
+        symlink_dir(original, link)
+    } else {
+        symlink_file(original, link)
+    }
```
Comment (yuja) [inline lib/src/file_util.rs:162]: Perhaps, the `original` file kind should be passed by caller (based on the repository data, not on the actual filesystem state.) It's scary to access the `original` path here. The path may point to arbitrary filesystem location.

Oh, does it also mean the `original` path can't be switched between file and directory once the symlink is created?

Comment (gulbanana) [reply lib/src/file_util.rs:162]: The way it works on Windows is that the symlink itself is to a directory or to a file. If you change the target to be the other thing, it just stops working until you change it back. Here's an example:
3k9uqVx 1

What kind of path-switching do you have in mind?

**Comment by ilyagr** [comment]
Optionally, it would be nice to update `docs/windows.md` in this commit. This could also be done in a separate PR.

File: lib/src/file_util.rs [hunk 2]
```diff
@@ -134,6 +146,39 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+    .map_err(|err| {
+        if let Some(ERROR_PRIVILEGE_NOT_HELD) = err.raw_os_error() {
```
Comment (martinvonz) [inline lib/src/file_util.rs:164]: This `if let` statement doesn't seem to bind any value, so can it be written as `if err.raw_os_error() == Some(ERROR_PRIVILEGE_NOT_HELD)`?

File: lib/tests/test_local_working_copy.rs
Comment (martinvonz) [inline lib/tests/test_local_working_copy.rs:1]: I would prefer to see the tests in the same commit (and the doc update too). Do tests pass after the first commit? If not, they should definitely be squashed into that commit.

File: lib/tests/test_local_working_copy.rs [hunk 3]
```diff
@@ -198,10 +197,32 @@ fn test_checkout_file_transitions(backend: TestRepoBackend) {
...
-        .unwrap();
-    ws.check_out(repo.op_id().clone(), None, &right_commit)
-        .unwrap();
+    match ws.check_out(repo.op_id().clone(), None, &left_commit) {
+        Err(CheckoutError::Other { err: outer_err, .. }) => {
+            match outer_err.downcast::<SymlinkError>() {
+                Ok(inner_err)
+                    if matches!(*inner_err, SymlinkError::DeveloperModeNotEnabledError) =>
+                {
+                    return
```
Comment (martinvonz) [inline lib/tests/test_local_working_copy.rs:206]: Does this mean we skip the entire test case if developer mode is not enabled? I think we still want to check that we can update between symlinks and that snapshotting works without removing the file when developer mode is not enabled.

File: lib/src/local_working_copy.rs [hunk 4]
```diff
@@ -1177,24 +1176,16 @@ impl TreeState {
...
-        }
+        let target = PathBuf::from(&target);
+        try_symlink(&target, disk_path).map_err(|err| CheckoutError::Other {
+            message: format!(
+                "Failed to create symlink from {} to {}",
+                disk_path.display(),
+                target.display()
+            ),
+            err: err.into(),
+        })?;
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs:1188]: Shouldn't we continue to just print a warning if developer mode is not enabled? Otherwise this commit gives the users who don't have developer mode enabled a worse experience, IIUC.

File: lib/src/file_util.rs (hunk 1 above)
Comment (yuja) [reply lib/src/file_util.rs:162]: > What kind of path-switching do you have in mind?

Directory->file on `jj new REV` for example. `jj` wouldn't recreate the symlink itself so long as the symlink data (the `original` path) is unchanged. If git were modeled after Windows symlinks, directory-symlink and file-symlink would be recorded differently, but it's not.

Comment (gulbanana) [reply lib/src/file_util.rs:162]: I see the problem. I'll look at the tree data structures and see what it would take to pass the information through.

Comment (gulbanana) [reply lib/src/file_util.rs:162]: I looked into this and, as you say, git doesn't store the information we'd need. It just has a relative path, and so that's all `MaterializedTreeValue::Symlink` contains; `TreeState::write_symlink` just receives an absolute and a relative path. We can still implement this, but it's a bit janky: 

`TreeState` knows it's writing a symlink of unknown valence, so it can determine whether it's intended to refer to a directory using `std::path::Path`, and pass this information to the low-level `try_symlink`. Unix can just ignore the flag. Windows has to test whether a symlink of the opposite type already exists, and if so, remove it; then, continue as before.

I've tested this approach and it works in practice. In some future where the backend has sufficiently rich information, we could extract the information from there instead of heuristically determining it in TreeState.

File: lib/src/local_working_copy.rs (hunk 4 above)
Comment (gulbanana) [reply lib/src/local_working_copy.rs]: I implemented this, but found out that skipping the symlink doesn't actually make the checkout work - it's too robust :) The status quo is that this fails entirely:
```
ignoring symlink at \\?\C:\Users\banana\Documents\code\jj\docs\cli-reference.md
Internal error: Failed to check out commit ba70a0c722af06485cb47bf5609eddfc60290a48: Failed to stat file \\?\C:\Users\banana\Documents\code\jj\docs\cli-reference.md: The system cannot find the file specified. (os error 2)
```

I've added a case to CheckoutError so that we get a single structured error message, rather than a skip followed by a generic internal error. To make checkout *work* with symlink support disabled, we'd have to do something like Git's solution of encoding them as text files (and even that doesn't give you an actually-functional source tree).

File: lib/tests/test_local_working_copy.rs (hunk 3 above)
Comment (gulbanana) [reply lib/tests/test_local_working_copy.rs]: I've added a function in testlib which can check whether we only failed because of missing symlink support and continue. However, this didn't put things in a sufficiently useful state to actually do any partial testing (see below or in discord for more than that) - so I just made it skip the test after all :(

That's better than the status quo - previously the tests were being unconditionally skipped on windows - but I'm not sure how we can have a partially functional test. The checkout process deliberately fails if it isn't able to produce a tree equivalent to what should be in the working copy (and that's a good thing). I think we'd need to break the tests up into smaller units, rather than trying to integration-test a subsystem with an internal failure.

File: lib/tests/test_local_working_copy.rs
Comment (gulbanana) [reply lib/tests/test_local_working_copy.rs:1]: They do pass, but only because they're disabled! I've squashed them.

File: lib/src/file_util.rs (hunk 2 above)
Comment (gulbanana) [reply lib/src/file_util.rs]: Fixed. This was just me running up against the limits of my Rust knowledge - I didn't know about `Option<T>`s' `impl Eq where T : Eq`.

**Comment by gulbanana** [comment]
> Optionally, it would be nice to update `docs/windows.md` in this commit. This could also be done in a separate PR.
> 
> You could say:
> 
> > ### Symbolic link support
> > `jj` supports symlinks on Windows under the following conditions:
> > 
> > * winver 14972 or higher (Windows 10+)
> > * "Developer Mode" is on
> > 
> > If those conditions are not satisfied, `jj` will (for now) crash when the working copy contains symlinks.
> 
> It might also be worth adding that, for colocated repos to work, the git option must be set. (Again, this can go in separately if it's a chore)

I've updated those docs, and addressed (I think!) the requested changes.

File: lib/src/file_util.rs (hunk 1 above)
Comment (ilyagr) [reply lib/src/file_util.rs:171]: > That's kind of true, but the use of Path::is_dir() has problems...

This feels like a Windows problem.  I wonder if it's feasible for jj to just create a "file" type symlink whenever it's unsure. We could do that if the link points outside the repo, as well.

For example, does something terrible happen on Windows if you create a symlink to a file and then replace the target file with a dir? Even if it does not work any longer, we can argue it's a Windows limitation we can't handle.

File: docs/windows.md [hunk 5]
```diff
@@ -62,3 +62,13 @@ Then only use the `~/my-repo` workspace from Linux.
...
+
+## Symbolic link support
+
+`jj` supports symlinks on Windows only when they arere enabled by the operating 
+system. This requires Windows 10 version 14972 or higher, as well as Developer
+Mode. If those conditions are not satisfied, `jj` will (for now) crash when the
+working copy contains symlinks. 
+
+For colocated repositories, `git` symlink support must also be enabled using the
+config option `core.symlinks=true`.
```
Comment (ilyagr) [inline docs/windows.md:74]: Let's emphasize that this is a Git config option.

File: lib/src/file_util.rs [hunk 6]
```diff
@@ -134,6 +148,47 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+    link: Q,
+    is_dir: bool,
+) -> Result<(), SymlinkError> {
+    const ERROR_PRIVILEGE_NOT_HELD: i32 = 1314;
+
+    // test whether the symlink already exists as the wrong *kind* of
+    // link (directory vs file); if so we have to recreate it
+    if is_dir && matches!(symlink_metadata(link.as_ref()), Ok(meta) if !meta.is_dir()) {
+        remove_dir(link.as_ref()).map_err(SymlinkError::InternalError)?;
+    }
```
Comment (yuja) [inline lib/src/file_util.rs:165]: What if `!is_dir` and directory symlink already exists?

(I don't know if symlink can be overwritten on Windows, so ignore me if that just works.)

File: lib/src/file_util.rs [hunk 7]
```diff
@@ -15,6 +15,12 @@
 #![allow(missing_docs)]
 
 use std::fs::{self, File};
+#[cfg(windows)]
+use std::fs::{remove_dir, symlink_metadata};
+#[cfg(unix)]
+use std::os::unix::fs::symlink;
+#[cfg(windows)]
+use std::os::windows::fs::{symlink_dir, symlink_file};
```
Comment (yuja) [inline lib/src/file_util.rs:23]: nit: (at your option) these `use` statements can be moved inside the function.

File: lib/src/file_util.rs [hunk 8]
```diff
@@ -29,6 +35,14 @@ pub struct PathError {
     pub error: io::Error,
 }
 
+#[derive(Debug, Error)]
+pub enum SymlinkError {
+    #[error("Developer Mode not enabled")]
+    DeveloperModeNotEnabled,
+    #[error("Symlink creation failed")]
+    InternalError(#[source] std::io::Error),
```
Comment (yuja) [inline lib/src/file_util.rs:43]: nit: `Io(..)` instead of `InternalError(..)`?

File: lib/src/local_working_copy.rs [hunk 9]
```diff
@@ -1177,24 +1176,23 @@ impl TreeState {
...
-                message: format!(
-                    "Failed to create symlink from {} to {}",
-                    disk_path.display(),
-                    target.display()
-                ),
-                err: err.into(),
-            })?;
-        }
+        let target = PathBuf::from(&target);
+        try_symlink(&target, disk_path, Path::is_dir(disk_path)).map_err(|inner_err| {
```
Comment (yuja) [inline lib/src/local_working_copy.rs:1181]: maybe you mean something like `disk_path.parent().join(target).is_dir()`?

(But see also the comment in the previous discussion https://github.com/martinvonz/jj/pull/2939#discussion_r1481542573)

File: lib/src/file_util.rs (hunk 1 above)
Comment (yuja) [reply lib/src/file_util.rs:171]: > This feels like a Windows problem. I wonder if it's feasible for jj to just create a "file" type symlink whenever it's unsure. We could do that if the link points outside the repo, as well.

Yeah, I think that's pretty okay. I also think using normal file is good as the minimal support. It will avoid path separator `/` vs `\\` issues and weird symlinks like `///`.

File: lib/src/file_util.rs (hunk 6 above)
Comment (gulbanana) [reply lib/src/file_util.rs:165]: It can be overwritten, as long as you're overwriting a link-to-directory with a link-to-directory (and so on for files).

File: docs/windows.md (hunk 5 above)
Comment (gulbanana) [reply docs/windows.md:74]: Reworded

File: lib/src/file_util.rs (hunk 8 above)
Comment (gulbanana) [reply lib/src/file_util.rs:43]: Fixed

File: lib/src/file_util.rs (hunk 6 above)
Comment (yuja) [reply lib/src/file_util.rs:195]: then we'll need to handle link-to-dir -> link-to-file case, too?

ah, btw, `symlink()` on Unix fails if the entry already exists. The existing entry should have been deleted by TreeState or LocalWorkingCopy, so we wouldn't have to do `remove_dir()` or `remove_file()`.

**Comment by gulbanana** [comment]
I've modified the previous approach based on Martin's patch to create regular files on unsupported platforms. The supportness check goes from a cfg to a flag stored in the TreeState - always true on unix, true on windows if Developer Mode is enabled; turns out we can check that by looking in the registry. The symlink tests are now enabled on all platforms.

I've also addressed the other feedback, with the possible exception of the concern in https://github.com/martinvonz/jj/pull/2939#discussion_r1482755218 - @yuja may want to weigh in.

File: lib/src/file_util.rs (hunk 1 above)
Comment (gulbanana) [reply lib/src/file_util.rs:201]: > For example, does something terrible happen on Windows if you create a symlink to a file and then replace the target file with a dir? Even if it does not work any longer, we can argue it's a Windows limitation we can't handle.

The symlink stops working, and JJ is unable to materialize or even `op restore`. You can recover from it, but only by deleting the bad symlink externally.

File: lib/src/local_working_copy.rs (hunk 9 above)
Comment (yuja) [reply lib/src/local_working_copy.rs:1206]: Isn't it the function to create the `disk_path` link? Also, the `target` directory/file might not be materialized yet. See https://github.com/martinvonz/jj/pull/2939#discussion_r1481542573.

Comment (gulbanana) [reply lib/src/local_working_copy.rs:1206]: I think I see the cause of the confusion. I’ve misunderstood Path::is_dir(); I didn’t think it did I/O. My goal was to *calculate* the directory-ness of the path at which the symlink should be created, since (as you say) neither the link nor its target may exist on disk yet; I see now that isn’t possible. 

Here’s a backup plan which I’ll implement in another revision of the branch: check whether the symlink’s target is a repo-relative path; if so, and it’s in the tree, it must be a file. If it’s relative but not in the tree, it’s a directory. If it points outside the tree (can this happen?), we can stat the target. If it points outside the tree but to a file or directory that doesn’t exist… I don’t know. An error saying “please don’t create symlinks to paths outside the repository”??

Comment (yuja) [reply lib/src/local_working_copy.rs:1206]: > check whether the symlink’s target is a repo-relative path; if so, and it’s in the tree, it must be a file. If it’s relative but not in the tree, it’s a directory. 

nit: if it's a symlink, check recursively (with some cycle detection.)

> If it points outside the tree, we could stat the target.

I would avoid stating external files because it's scary if `jj` read arbitrary unmanaged data (though leaking file node type wouldn't be a security issue.) I think it's okay to fall back to a file symlink (or a normal text file) in that case.

BTW, in the initial implementation, I think it's okay to always assume symlinks as file links. The user can fix it up manually so long as `jj` can read both file and directory symlinks.

**Comment by gulbanana** [comment]
I think that's everything for now.

File: lib/src/file_util.rs [hunk 10]
```diff
@@ -146,6 +162,51 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
     }
 }
 
+/// Symlinks are always available on UNIX, but on Windows they may not be
+/// enabled
```
Comment (martinvonz) [inline lib/src/file_util.rs:166]: nit: instead of duplicating this description, i would put only "Symlinks are always available on UNIX" here and then below a short description of when they are available on windows

File: lib/src/file_util.rs [hunk 11]
```diff
@@ -146,6 +162,51 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+}
+
+/// Symlinks are always available on UNIX, but on Windows they may not be
+/// enabled
+#[cfg(windows)]
+pub fn check_symlink_support() -> Result<bool, std::io::Error> {
+    let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
+    let sideloading =
+        hklm.open_subkey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock")?;
+    let developer_mode: u32 = sideloading.get_value("AllowDevelopmentWithoutDevLicense")?;
```
Comment (martinvonz) [inline lib/src/file_util.rs:179]: Will the error message make sense to a user? Maybe we should map it to something more readable (like "Failed to determine if symlinks are supported because <that long key name> wasn't readable"). Actually, none of the callers seem to care about the error, so just return false here instead when we fail to read them instead? How common is it that we would fail to read it?

File: lib/src/local_working_copy.rs [hunk 12]
```diff
@@ -1204,28 +1201,23 @@ impl TreeState {
...
-        {
-            self.write_file(disk_path, &mut target.as_bytes(), false)
-        }
-        #[cfg(unix)]
-        {
-            let target = PathBuf::from(&target);
-            symlink(&target, disk_path).map_err(|err| CheckoutError::Other {
+        let target = PathBuf::from(&target);
+        try_symlink(&target, disk_path).map_err(|inner_err| match inner_err {
+            SymlinkError::DeveloperModeNotEnabled => CheckoutError::SymlinkNotSupported(inner_err),
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs:1207]: This shouldn't happen since we checked the registry, right? I want to avoid errors when updating the working copy whether or not developer mode is enabled. I think it's fine if this only happens if the user had enabled developer mode, then ran `jj new <something>` and disabled developer mode while that was running. But that's such a rare case that I don't think we need a special message for it; just map it to an io::Error.

File: CHANGELOG.md
Comment (martinvonz) [inline CHANGELOG.md:1]: nit: squash this commit into the parent (we would want to cherry-pick or roll them back as one unit)

File: docs/windows.md [hunk 13]
```diff
@@ -62,3 +62,13 @@ Then only use the `~/my-repo` workspace from Linux.
 
 [issue-2040]: https://github.com/martinvonz/jj/issues/2040
 [array-op]: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7.4#the-array-sub-expression-operator
+
+## Symbolic link support
+
+`jj` supports symlinks on Windows only when they arere enabled by the operating
```
Comment (martinvonz) [inline docs/windows.md:68]: nit: typo in "arere"

File: docs/windows.md [hunk 14]
```diff
@@ -62,3 +62,13 @@ Then only use the `~/my-repo` workspace from Linux.
...
+
+## Symbolic link support
+
+`jj` supports symlinks on Windows only when they arere enabled by the operating 
+system. This requires Windows 10 version 14972 or higher, as well as Developer
+Mode. If those conditions are not satisfied, `jj` will materialize symlinks as
+ordinary files.
+
+For colocated repositories, Git support must also be enabled using the
+`git config` option `core.symlinks=true`.
```
Comment (martinvonz) [inline docs/windows.md:74]: Thanks for documenting it and remembering to mention colocated repos.

File: lib/src/local_working_copy.rs [hunk 15]
```diff
@@ -549,6 +548,7 @@ impl TreeState {
             file_states: FileStatesMap::new(),
             sparse_patterns: vec![RepoPathBuf::root()],
             own_mtime: MillisSinceEpoch(0),
+            symlink_support: check_symlink_support().unwrap_or(false),
```
Comment (yuja) [inline lib/src/local_working_copy.rs:551]: Perhaps, `get_updated_tree_value()` can also be changed to use this flag?
```rust
            let current_tree_values = current_tree.path_value(repo_path);
            let new_file_type = if cfg!(windows) { // XXX HERE
                let mut new_file_type = new_file_state.file_type.clone();
                if matches!(new_file_type, FileType::Normal { .. })
                    && matches!(current_tree_values.as_normal(), Some(TreeValue::Symlink(_)))
                {
                    new_file_type = FileType::Symlink;
                }
                new_file_type
            } else {
                new_file_state.file_type.clone()
            };
```

File: lib/src/file_util.rs [hunk 16]
```diff
@@ -146,6 +162,51 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+}
+
+#[cfg(unix)]
+pub fn try_symlink<P: AsRef<Path>, Q: AsRef<Path>>(
+    original: P,
+    link: Q,
+) -> Result<(), SymlinkError> {
+    symlink(original, link).map_err(SymlinkError::Io)
+}
+
```
Comment (yuja) [inline lib/src/file_util.rs:209]: nit: since there are multiple platform-specific functions, they can be organized as inner modules (if you prefer):

```rust
pub use self::platform::*;

#[cfg(unix)]
mod platform {
}

#[cfg(windows)]
mod platform {
}
```

File: Cargo.lock
[the remark this answers is not in the document]
Comment (gulbanana) [reply Cargo.lock:1]: fixed. i must have done something wrong with a squash

File: CHANGELOG.md
Comment (gulbanana) [reply CHANGELOG.md:1]: done

File: lib/src/file_util.rs (hunk 10 above)
Comment (gulbanana) [reply lib/src/file_util.rs:166]: done

File: lib/src/file_util.rs (hunk 11 above)
Comment (gulbanana) [reply lib/src/file_util.rs:179]: I don't know of a case when reading the registry entry would fail - you'd have to have some weird broken environment. On the other hand, if the environment is that broken I'd want to know about it!

File: lib/src/local_working_copy.rs (hunk 12 above)
Comment (gulbanana) [reply lib/src/local_working_copy.rs:1207]: Originally this error variant existed for tests to use, but the tests can now use check_symlink_support() instead. I've removed it.

File: docs/windows.md (hunk 13 above)
Comment (gulbanana) [reply docs/windows.md:68]: fixed

File: lib/src/file_util.rs (hunk 16 above)
Comment (gulbanana) [reply lib/src/file_util.rs:209]: sure, i've done that and moved the platform-specific use statements inside the inner modules

File: lib/src/local_working_copy.rs (hunk 15 above)
Comment (gulbanana) [reply lib/src/local_working_copy.rs:551]: good catch, i've changed it

**Comment by gulbanana** [comment]
Addressed feedback and rebased.

File: CHANGELOG.md [hunk 17]
```diff
@@ -73,9 +73,11 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ### Fixed bugs
 
-* On Windows, symlinks in the repo are now materialized as regular files in the
+* On Windows, symlinks in the repo are now are now supported when Developer Mode is enabled.
```
Comment (yuja) [inline CHANGELOG.md:76]: nit: double "are now"

File: lib/src/file_util.rs [hunk 18]
```diff
@@ -146,6 +148,54 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+    use std::io;
+    use std::os::unix::fs::symlink;
+    use std::path::Path;
+
+    /// Symlinks are always available on UNIX
+    pub fn check_symlink_support() -> io::Result<bool> {
+        Ok(true)
+    }
+
+    #[cfg(unix)]
```
Comment (yuja) [inline lib/src/file_util.rs:162]: nit: redundant `#[cfg(unix)]`

File: lib/src/file_util.rs [hunk 19]
```diff
@@ -146,6 +148,54 @@ pub fn persist_content_addressed_temp_file<P: AsRef<Path>>(
...
+    /// Developer Mode setting, which is stored in the registry key below.
+    pub fn check_symlink_support() -> io::Result<bool> {
+        let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
+        let sideloading =
+            hklm.open_subkey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock")?;
+        let developer_mode: u32 = sideloading.get_value("AllowDevelopmentWithoutDevLicense")?;
+        Ok(developer_mode == 1)
+    }
+
+    #[cfg(windows)]
```
Comment (yuja) [inline lib/src/file_util.rs:187]: ditto

File: CHANGELOG.md
Comment (yuja) [inline CHANGELOG.md:1]: In commit message:
>    working_copy: implement symlinks on Windows with a helper function
>    tests: enable symlink tests on windows, ignoring failures due to disabled developer mode
>    docs: add note on Windows symlink support

Maybe not updated after squashing?

File: lib/src/file_util.rs (hunk 11 above)
Comment (yuja) [reply lib/src/file_util.rs]: > if the environment is that broken I'd want to know about it! I think we should bubble this up like other rare IO-level errors.

Perhaps, tests can be updated to `.unwrap()` the result then? We can also make `TreeState::symlink_support` be evaluated lazily to propagate the error, but I don't know if that'll be worth the added complexity.

**Review by yuja — APPROVED** [review]
lgtm, thanks.

File: CHANGELOG.md
Comment (gulbanana) [reply CHANGELOG.md:1]: That was deliberate, since it changes all three things - but I take it this is not the right style to use!

File: CHANGELOG.md (hunk 17 above)
Comment (gulbanana) [reply CHANGELOG.md:76]: cripes, how did i make so many typos... i think i've been been doing something as i learn `jj move` workflows. fixed!

File: lib/src/file_util.rs (hunk 18 above)
Comment (gulbanana) [reply lib/src/file_util.rs:162]: removed

File: lib/src/file_util.rs (hunk 19 above)
Comment (gulbanana) [reply lib/src/file_util.rs:187]: also removed

File: CHANGELOG.md
Comment (gulbanana) [reply CHANGELOG.md:1]: I've updated the description to the multi-paragraph style that's used in other finished commits

File: lib/src/file_util.rs (hunk 11 above)
Comment (gulbanana) [reply lib/src/file_util.rs]: the tests are using unwrap() :)
