### PR TITLE
sign: Hide tests behind feature

### LINKED ISSUE #3096: GPG signing tests fail on my machine (when `gpg` is not installed)
I'm getting these errors at commit 84685a4. I haven't investigated it, but perhaps @julienvincent has some idea? They seem to pass in the CI.

```
🐠 RUST_BACKTRACE=1 cargo insta test --accept --workspace --test-runner nextest -N -- test_gpg
    Finished test [unoptimized + debuginfo] target(s) in 0.11s
    Starting 4 tests across 9 binaries (1040 skipped)
        FAIL [   0.053s] jj-lib::runner test_gpg::unknown_key

--- STDOUT:              jj-lib::runner test_gpg::unknown_key ---

running 1 test
test test_gpg::unknown_key ... FAILED

failures:

failures:
    test_gpg::unknown_key

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 309 filtered out; finished in 0.05s


--- STDERR:              jj-lib::runner test_gpg::unknown_key ---
thread 'test_gpg::unknown_key' panicked at lib/tests/test_gpg.rs:56:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1077:23
   4: runner::test_gpg::GpgEnvironment::new
             at ./tests/test_gpg.rs:48:23
   5: runner::test_gpg::unknown_key
             at ./tests/test_gpg.rs:145:15
   6: runner::test_gpg::unknown_key::{{closure}}
             at ./tests/test_gpg.rs:144:17
   7: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

        FAIL [   0.054s] jj-lib::runner test_gpg::gpg_singing_roundtrip

--- STDOUT:              jj-lib::runner test_gpg::gpg_singing_roundtrip ---

running 1 test
test test_gpg::gpg_singing_roundtrip ... FAILED

failures:

failures:
    test_gpg::gpg_singing_roundtrip

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 309 filtered out; finished in 0.05s


--- STDERR:              jj-lib::runner test_gpg::gpg_singing_roundtrip ---
thread 'test_gpg::gpg_singing_roundtrip' panicked at lib/tests/test_gpg.rs:56:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1077:23
   4: runner::test_gpg::GpgEnvironment::new
             at ./tests/test_gpg.rs:48:23
   5: runner::test_gpg::gpg_singing_roundtrip
             at ./tests/test_gpg.rs:90:15
   6: runner::test_gpg::gpg_singing_roundtrip::{{closure}}
             at ./tests/test_gpg.rs:89:27
   7: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

        FAIL [   0.054s] jj-lib::runner test_gpg::invalid_signature

--- STDOUT:              jj-lib::runner test_gpg::invalid_signature ---

running 1 test
test test_gpg::invalid_signature ... FAILED

failures:

failures:
    test_gpg::invalid_signature

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 309 filtered out; finished in 0.05s


--- STDERR:              jj-lib::runner test_gpg::invalid_signature ---
thread 'test_gpg::invalid_signature' panicked at lib/tests/test_gpg.rs:56:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1077:23
   4: runner::test_gpg::GpgEnvironment::new
             at ./tests/test_gpg.rs:48:23
   5: runner::test_gpg::invalid_signature
             at ./tests/test_gpg.rs:176:15
   6: runner::test_gpg::invalid_signature::{{closure}}
             at ./tests/test_gpg.rs:175:23
   7: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

        FAIL [   0.054s] jj-lib::runner test_gpg::gpg_signing_roundtrip_explicit_key

--- STDOUT:              jj-lib::runner test_gpg::gpg_signing_roundtrip_explicit_key ---

running 1 test
test test_gpg::gpg_signing_roundtrip_explicit_key ... FAILED

failures:

failures:
    test_gpg::gpg_signing_roundtrip_explicit_key

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 309 filtered out; finished in 0.05s


--- STDERR:              jj-lib::runner test_gpg::gpg_signing_roundtrip_explicit_key ---
thread 'test_gpg::gpg_signing_roundtrip_explicit_key' panicked at lib/tests/test_gpg.rs:56:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/result.rs:1077:23
   4: runner::test_gpg::GpgEnvironment::new
             at ./tests/test_gpg.rs:48:23
   5: runner::test_gpg::gpg_signing_roundtrip_explicit_key
             at ./tests/test_gpg.rs:114:15
   6: runner::test_gpg::gpg_signing_roundtrip_explicit_key::{{closure}}
             at ./tests/test_gpg.rs:113:40
   7: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/d44e3b95cb9d410d89cb8ab3233906a33f43756a/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

------------
     Summary [   0.055s] 4 tests run: 0 passed, 4 failed, 1040 skipped
        FAIL [   0.054s] jj-lib::runner test_gpg::gpg_signing_roundtrip_explicit_key
        FAIL [   0.054s] jj-lib::runner test_gpg::gpg_singing_roundtrip
        FAIL [   0.054s] jj-lib::runner test_gpg::invalid_signature
        FAIL [   0.053s] jj-lib::runner test_gpg::unknown_key
error: test run failed
done: no snapshots to review
```

- Platform: MacOS

```
🐠 rustc -Vv
rustc 1.78.0-nightly (d44e3b95c 2024-02-09)
binary: rustc
commit-hash: d44e3b95cb9d410d89cb8ab3233906a33f43756a
commit-date: 2024-02-09
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 17.0.6
```

### PR DESCRIPTION
**Pull request by julienvincent**
This adds a cargo feature `signing-tests` which is used to disable the gpg and ssh signing tests unless set.

This is done in order to avoid requiring all collaborators to have setup all the tools on their local machines that are required to test commit signing.

---

Not sure if this is the best way to address this.

Closes #3096

### CODE REVIEW

**Comment by martinvonz** [comment]
> Not sure if this is the best way to address this.

I think I agree with @yuja's [comment](https://github.com/martinvonz/jj/issues/3096#issuecomment-1954003754) saying that this will mostly make people run these tests less (even if they have gpg and ssh installed) and not notice failures until CI.

**Comment by julienvincent** [comment]
I'll update this later this evening 👍🏻

**Comment by julienvincent** [comment]
Sorry I didn't get a chance to address this today. Will tackle first thing in the morning.

**Comment by julienvincent** [comment]
I updated to conditionally run only if gpg is installed. @yuja Please can you take a look.

File: lib/tests/test_gpg.rs [hunk 1]
```diff
@@ -75,6 +75,18 @@ impl GpgEnvironment {
     }
 }
 
+// This will only run the `test` fn if gpg is installed on the system
+fn run_with_guard<F>(test: F)
```
Comment (yuja) [inline lib/tests/test_gpg.rs:79]: nit: (at your option) can be expressed as `test: impl FnOnce()`

File: lib/tests/test_gpg.rs [hunk 2]
```diff
@@ -75,6 +75,18 @@ impl GpgEnvironment {
...
+where
+    F: FnOnce(),
+{
+    if Command::new("gpgaa").arg("--version").status().is_err() {
```
Comment (yuja) [inline lib/tests/test_gpg.rs:83]: "gpg"

File: lib/tests/test_gpg.rs [hunk 3]
```diff
@@ -75,6 +75,18 @@ impl GpgEnvironment {
...
+        eprintln!("Skipping because gpg is not installed on the system");
+        return;
+    }
+    test();
+}
+
```
Comment (yuja) [inline lib/tests/test_gpg.rs:89]: nit: alternatively, this could be a declarative macro. I don't know which is better overall. Both approaches have pros and cons.

```rust
macro_rules! gpg_guard {
    () => {
        if Command::new("gpg").arg("--version").status().is_err() {
            eprintln!("Skipping because gpg is not installed on the system");
            return;
        }
    };
}

```

**Review by yuja — APPROVED** [review]
Thanks!

File: lib/tests/test_gpg.rs (hunk 2 above)
Comment (julienvincent) [reply lib/tests/test_gpg.rs:83]: Ahh 🤦🏻 This was from my testing. Thanks

File: lib/tests/test_gpg.rs (hunk 3 above)
Comment (julienvincent) [reply lib/tests/test_gpg.rs:89]: Nice! Never used macros before. This looks nice to me will use this. Out of interest what would you consider the pros and cons in this context?

Comment (yuja) [reply lib/tests/test_gpg.rs:86]: closure: + obvious control flow, - nesting
macro: + less noisy, - hidden return statement
