### PR TITLE
local_working_copy: when all sides of a conflict are executable, mate…

### LINKED ISSUE #3579: Conflict on rebase clears execute flag on script
## Description
If a script in a repo has perms 755, but a rebase causes a conflict in the script, the conflicted file's perms get set to 644 and remain so after the conflict is resolved.

## Steps to Reproduce the Problem
1.  Run this script to create a repo and introduce a conflict:
    ```bash
    #!/usr/bin/env bash
    
    mkdir /tmp/repro_permfail
    cd /tmp/repro_permfail/
    jj git init
    cat <<EOF > script.sh
    #!/usr/bin/bash
    echo "No conflict here."
    EOF
    chmod 755 script.sh
    jj desc -m "script import"
    jj new -m "set up for conflict"
    cat <<EOF >> script.sh
    echo "Half a conflict."
    EOF
    jj new -r @- -m "create a conflict"
    cat <<EOF >> script.sh
    echo "The other half."
    EOF
    ```
1. Now rebase the "create a conflict" revision onto the "set up for conflict" revision.  This will create a conflict:  `jj rebase -r <REV1> -d <REV2>`  (I don't know how to script that, unfortunately...)
1. `jj new -r REV1` to resolve the conflict.

## Expected Behavior
The permissions on `script.sh` remain 755.

## Actual Behavior
The permissions on `script.sh` are changed to 644 in the conflicted state and remain so after resolution.

## Specifications

- Platform: macOS 14.4.1 (Sonoma)
- Version: `jj 0.16.0`

### PR DESCRIPTION
**Pull request by gulbanana**
local_working_copy: when all sides of a conflict are executable, materialise the conflicted file as executable

Fixes #3579 and adds a testcase for an executable conflict treevalue.

### CODE REVIEW

**Comment by gulbanana** [comment]
The new test fails before the fix and passes after it. This repro script can also be used to verify:

```sh
#!/usr/bin/env bash

mkdir repro_permfail
cd repro_permfail/

jj git init

cat <<EOF > script.sh
#!/usr/bin/bash
echo "No conflict here."
EOF
chmod 755 script.sh

jj desc -m "script import"
jj new -m "set up for conflict"
jj branch create setup-conflict
cat <<EOF >> script.sh
echo "Half a conflict."
EOF

jj new -r @- -m "create a conflict"

cat <<EOF >> script.sh
echo "The other half."
EOF

jj rebase -d setup-conflict
```

File: lib/src/local_working_copy.rs [hunk 1]
```diff
@@ -1238,8 +1239,7 @@ impl TreeState {
                 err: err.into(),
             })?;
         let size = conflict_data.len() as u64;
-        // TODO: Set the executable bit correctly (when possible) and preserve that on
-        // Windows like we do with the executable bit for regular files.
```
Comment (yuja) [inline lib/src/local_working_copy.rs:1242]: I think the Windows issue still exist. The comment can be moved to `write_path_to_store()`?

File: lib/src/local_working_copy.rs [hunk 2]
```diff
@@ -1223,6 +1223,7 @@ impl TreeState {
         &self,
         disk_path: &Path,
         conflict_data: Vec<u8>,
+        executable: bool,
```
Comment (yuja) [inline lib/src/local_working_copy.rs:1226]: copy to `FileState::for_file(_, ..)`?

File: lib/src/merge.rs [hunk 3]
```diff
@@ -501,6 +501,13 @@ impl MergedTreeValue {
                 .all(|value| matches!(value, Some(TreeValue::Tree(_)) | None))
     }
 
+    /// Whether this merge would resolve to an executable file
+    pub fn is_executable(&self) -> bool {
+        self.values
+            .iter()
+            .all(|v| matches!(*v, Some(TreeValue::File { executable, .. }) if executable))
+    }
```
Comment (yuja) [inline lib/src/merge.rs:509]: handle `is_present()` and `None` like `.is_tree()`?

Absent values should be excluded as we do in `to_file_merge()`. I'm not sure if an empty merge should be considered an executable, though.

File: lib/src/local_working_copy.rs (hunk 1 above)
Comment (martinvonz) [reply lib/src/local_working_copy.rs:1242]: Agreed. And it's probably not very hard to fix it there if you're interested, but feel free to leave it for later.

Comment (gulbanana) [reply lib/src/local_working_copy.rs:1242]: I see, the filemode issue doesn't repro on Windows so I didn't realise there was another one. I'll look deeper.

File: lib/src/merge.rs (hunk 3 above)
Comment (gulbanana) [reply lib/src/merge.rs:509]: Alright, I'll change that (or maybe look for a version with slightly less unwrap ;_;).

File: lib/src/local_working_copy.rs (hunk 2 above)
Comment (gulbanana) [reply lib/src/local_working_copy.rs:1226]: right, i missed the hardcoded `false` there

File: lib/src/merge.rs (hunk 3 above)
Comment (gulbanana) [reply lib/src/merge.rs:509]: ok, i've got it using a merge of the executable bits now, and we only consider the conflict treevalue executable if that merge resolves

File: lib/src/local_working_copy.rs (hunk 1 above)
Comment (gulbanana) [reply lib/src/local_working_copy.rs:1242]: ok, i think i understand this now - windows filesystems may not have `+x`, so we keep the last known value of the executable flag for ordinary files. i've done the same thing for conflicts:
```rs
                    #[cfg(windows)]
                    let executable = {
                        let () = executable; // use the variable
                        if let Some(merge) = current_tree_values.to_executable_merge() {
                            merge.into_resolved().unwrap_or(Some(false)).unwrap_or_default()
                        } else {
                            false
                        }
                    };
```

**Comment by gulbanana** [comment]
Thanks for the reviews. I've addressed the feedback, and added a second commit which fixes some clippy warnings which were output only on windows - turns out that the `cfg`ed out behaviour around the executable bit has been triggering lints, but our PR checks weren't catching them.

**Comment by martinvonz** [comment]
> added a second commit which fixes some clippy warnings which were output only on windows - turns out that the `cfg`ed out behaviour around the executable bit has been triggering lints, but our PR checks weren't catching them.

Thanks. I suppose we could also run clippy on windows. Not sure it's worth the resource cost given how infrequently it's going to find anything.

File: lib/src/local_working_copy.rs [hunk 4]
```diff
@@ -1392,8 +1397,13 @@ impl TreeState {
...
                     panic!("unexpected tree entry in diff at {path:?}");
                 }
-                MaterializedTreeValue::Conflict { id: _, contents } => {
-                    self.write_conflict(&disk_path, contents)?
+                MaterializedTreeValue::Conflict { id, contents } => {
+                    let executable = if let Some(merge) = id.to_executable_merge() {
+                        merge.resolve_trivial().copied().unwrap_or_default()
+                    } else {
+                        false
+                    };
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs:1405]: I think it would make sense to make the materialized executable bit part of `MaterializedTreeValue::Conflict`. That would also make the "mode" field in `jj diff --git` a bit more accurate. Feel free to leave that for later.

**Review by martinvonz — APPROVED** [review]
Thanks!

File: CHANGELOG.md [hunk 5]
```diff
@@ -16,7 +16,9 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 * `jj tag list` now prints commit summary along with the tag name.
 
 ### Fixed bugs
-
+* Files with conflicts are now checked out as executable if all sides of the 
+  conflict are executable.
```
[the remark this answers is not in the document]
Comment (gulbanana) [reply CHANGELOG.md:20]: The merge-based calculation is more sophisticated, but I think it still has basically the same effect. It's only if all sides of the merge are
- present
- executable 
that it gets trivially resolved to `true`. 

Or is there some other case that makes this not an [iff](https://en.wikipedia.org/wiki/If_and_only_if)?
