### PR TITLE
cli: avoid bad hint "Prefix the expression with 'all'..."

### LINKED ISSUE #2451: Bad hint about using `all:` prefix for non-existent revision
## Steps to Reproduce the Problem

1. `jj rebase -b all -d root`

## Actual Behavior

```
Error: Revision "root" doesn't exist
Hint: Prefix the expression with 'all' to allow any number of revisions (i.e. 'all:root').
```

## Expected Behavior

No hint about using `all:` since the revision was invalid. The hint should ideally show up only if the revset resolved to more than one revision.

Btw, the hint should probably include the `:` in `all:`.

## Specifications

- Platform: all
- Version: 0.10.0-a1ef9dc845da716a6a0a0834e2d5e7b3ce77b9df

### PR DESCRIPTION
**Pull request by zummenix**
There is no point of showing the hint for non-existent revision.

Also appends ':' to the 'all' to make the hint more precise.

Closes #2451

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]

File: cli/src/cli_util.rs [hunk 1]
```diff
@@ -808,17 +808,25 @@ Set which revision the branch points to with `jj branch set {branch_name} -r <RE
         if let Some(revision_str) = revision_str.strip_prefix("all:") {
             self.resolve_revset(revision_str)
         } else {
+            let matches_multiple_revisions = || {
+                self.parse_revset(revision_str)
+                    .is_ok_and(|revset_expression| {
+                        self.evaluate_revset(revset_expression)
+                            .is_ok_and(|revset| revset.iter().take(2).count() > 1)
+                    })
+            };
```
Comment (yuja) [inline cli/src/cli_util.rs:817]: Perhaps, better way to fix the problem is to extract the post-processing part of `resolve_single_rev()` to function, and pass `bool` or `Option<String>` to append the hint.

It doesn't make much sense to suggest `all:` if the commmit/branch is diverged/conflict for example.

Comment (zummenix) [reply cli/src/cli_util.rs]: I've extracted `resolve_single_rev()` into a separate function with additional `bool` flag.

**Review by yuja — APPROVED** [review]
Thanks!

**Comment by zummenix** [comment]
@martinvonz Could you please force cla rescan? Thank you!

**Comment by martinvonz** [comment]
> @martinvonz Could you please force cla rescan? Thank you!

Weird that it happened again. Done.
