### PR TITLE
Better respect `$NO_COLOR`

### LINKED ISSUE #5041: NO_COLOR is not correctly overridden by ui.color config
According to the docs, having NO_COLOR set in the environment, but having `ui.color` set to something like `always` should cause the NO_COLOR environment variable to get overridden, but it doesn't appear to work.

## Steps to Reproduce the Problem

1. `export NO_COLOR=1`
1. `jj diff` shows no color as expected
1. add `color="always"` to `[ui]` section of `~/.config/jj/config.toml`
1. `jj diff` still shows no color. interestingly, if `ui.diff.format` is set to `git`, the output shows some **bold** characters, but still no color. Perhaps this is a hint to where the issue lies.

- Platform: Tested on Mac + Linux
- Version: 0.24.0

### PR DESCRIPTION
**Pull request by martinvonz**
Closes #5041 

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by PhilipMetzger — APPROVED** [review]
Thanks

File: cli/src/formatter.rs [hunk 1]
```diff
@@ -161,6 +161,7 @@ impl FormatterFactory {
     }
 
     pub fn color(config: &StackedConfig, debug: bool) -> Result<Self, ConfigGetError> {
+        crossterm::style::force_color_output(true);
```
Comment (yuja) [inline cli/src/formatter.rs:164]: nit: Since this is a global flag, it might be better to do this in `CliRunner` or somewhere closer to `main()`.

**Review by yuja — APPROVED** [review]

File: cli/src/formatter.rs (hunk 1 above)
Comment (martinvonz) [reply cli/src/formatter.rs]: Yeah, I wasn't sure where the best place would be. I moved it to `CliRunner::run()`. PTAL.

**Review by yuja — APPROVED** [review]
