### PR TITLE
split: do not prevent all changes from going into the parent commit, and a fix

### LINKED ISSUE #4533: Split behavior differs when using diff editor and passing path
## Description

Just ran into the following scenario.

```
> jj new
> jj describe -m 'Exciting feature'
... Run into a bug.
... Fix the bug instead of working on the feature.
```

Ideally, what I want to do from here is "shove" the changes down one commit and specify a good commit message.

I expected `jj split` to be the tool for this but selecting all changes in the built-in diff editor quits the command with `Nothing changed.`

Sidenote: I understand that creation of an empty commit is probably usually undesirable but an empty commit with a commit message is not entirely empty. If this limitation is intentional, I hope there can be a flag to lift the restriction.

Two ways to achieve what I wanted came to mind.

```
> jj describe
... Copy the message to clipboard and edit
> jj new
> jj describe
... Paste clipboard
```

```
... Make a token change that will belong to the commit with the current message
> jj split
... Dig into the changes to find the token change
```

Neither of these feel like great UX. Luckily the [PATHS]... argument in the help for split caught my eye and I only had a single file with changes (manually listing a dozen files would be tedious). `jj split -- path/to/changed/file` to the rescue, adding all the changes to the first commit and allowing me to edit the message and copying the original message to the new empty commit for me.

In the end I got exactly what I wanted but the diff editor (especially the built-in one) making it impossible is unexpected and IMO a bug.

I did look for existing issues that express a desire to have split result in empty commits, #1155 is the closest I found and #3772 is somewhat similar but neither has quite the same expectations.

## Steps to Reproduce the Problem

1. `jj split`
1. Select all changes in the built-in diff editor and confirm

## Expected Behavior

Add all the changes to the first commit and create a new empty commit, offering to edit the original message for both.

## Actual Behavior

Outputs `Nothing changed.`, doesn't create any new commits.

## Specifications

- Platform:
  ```
  > uname -a
  Linux yorp 6.6.44 #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 06:54:42 UTC 2024 x86_64 GNU/Linux
  ```

- Version:
  ```
  > jj --version
  jj 0.17.1
  ```

### PR DESCRIPTION
**Pull request by samueltardieu**
Allowing to put everything into the first commit closes #4533.

**Question:** should we suggest using `jj undo` if everything was put into one of the two commits in case the user didn't want to do this? Or, do we want this only if, in addition, the empty commit has an empty description, because there should be no reason to create an empty commit?

# Checklist

If applicable:
- [X] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
Should most of the PR description be moved into the commit description (with s/PR/commit/ or similar)? The question makes sense in the PR description.

**Comment by samueltardieu** [comment]
> Should most of the PR description be moved into the commit description (with s/PR/commit/ or similar)? The question makes sense in the PR description.

It even led me to split the commits (using `split`, this is appropriate).

File: cli/tests/test_split_command.rs [hunk 1]
```diff
@@ -129,14 +129,14 @@ fn test_split_by_paths() {
     test_env.set_up_fake_editor();
     let (stdout, stderr) = test_env.jj_cmd_ok(&repo_path, &["split", "-r", "@-", "nonexistent"]);
     insta::assert_snapshot!(stdout, @"");
-    insta::assert_snapshot!(stderr, @r###"
-    Warning: The given paths do not match any file: nonexistent
+    insta::assert_snapshot!(stderr, @r#"
+    Warning: No changes have been selected, the first commit will be empty
```
Comment (martinvonz) [inline cli/tests/test_split_command.rs:134]: The current message was added by you in #1168. I wonder if you included it as a reminder to the user. Perhaps they did `jj split -r X *.rs` and the `*.rs` gets resolved by their shell and doesn't include a file that was added in X. But maybe that's a low-enough risk that we don't need to worry about it.

File: CHANGELOG.md [hunk 2]
```diff
@@ -101,6 +101,9 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 * Editing a hidden commit now makes it visible.
 
+* `jj split` will no longer reference the paths given on the command line when
+  none have been given in interactive mode.
```
Comment (martinvonz) [inline CHANGELOG.md:109]: I don't think this needs to be mentioned. I can't think of a user group who would care to learn this. It also doesn't seem like it should be considered a fixed bug.

File: cli/src/commands/split.rs [hunk 3]
```diff
@@ -109,12 +108,13 @@ the operation will be aborted.
...
-    if &selected_tree_id == commit.tree_id() && diff_selector.is_interactive() {
+    if &selected_tree_id == commit.tree_id() {
         // The user selected everything from the original commit.
-        writeln!(ui.status(), "Nothing changed.")?;
-        return Ok(());
-    }
-    if selected_tree_id == base_tree.id() {
+        writeln!(
+            ui.warning_default(),
+            "All changes have been selected, the second commit will be empty"
```
Comment (martinvonz) [inline cli/src/commands/split.rs:115]: nit: maybe use semicolon instead of comma since these are two full sentences. Oh, but this matches the other message below, so never mind

File: cli/src/commands/split.rs [hunk 4]
```diff
@@ -109,12 +108,13 @@ the operation will be aborted.
     // Prompt the user to select the changes they want for the first commit.
     let selected_tree_id =
         diff_selector.select(&base_tree, &end_tree, matcher.as_ref(), format_instructions)?;
-    if &selected_tree_id == commit.tree_id() && diff_selector.is_interactive() {
+    if &selected_tree_id == commit.tree_id() {
         // The user selected everything from the original commit.
```
Comment (martinvonz) [inline cli/src/commands/split.rs:112]: nit: might be nice to add ", so the second commit will be empty" to match the comment from the case below

**Review by martinvonz — APPROVED** [review]

File: cli/tests/test_split_command.rs (hunk 1 above)
Comment (samueltardieu) [reply cli/tests/test_split_command.rs:134]: Yeah, I don't remember why I added this, it was a long time ago.
