### PR TITLE
revset: for short hash, look up both commit and change ids to disambiguate

### LINKED ISSUE #799: `jj update` takes me to a *commit id* when I meant a *change id* with no warning
Repo state:  [jj_up_f798.tar.gz](https://github.com/martinvonz/jj/files/10097368/jj_up_f798.tar.gz)

My last command was `jj up f798` as I meant to get to the "Refactor errors" commit a.k.a. 508216 in the `jj log` output below (it's near the middle). However, I ended up at a very old commit without warning. In other cases, I saw `jj` warn me in this case, I think.

Separately, this is an example of an unexpected (to me) divergence from a recent build of `jj` similar to https://github.com/martinvonz/jj/issues/666. Unfortunately, I missed the exact moment it happened, and I'm not 100% sure that's a bug.

```
$ jj log
@ 6eb5df3ff40c ilyagr@users.noreply.github.com 2022-11-26 18:12:38.000 -08:00 80a0e8cc7a19
| (no description set)
| o c2a3c7d6c506 ilyagr@users.noreply.github.com 2022-11-24 18:31:47.000 -08:00 815745052ec0
| | NOTES: jj describe -r change, jj log -r change_confl_with_commit
| o f55d4d08eb8c ilyagr@users.noreply.github.com 2022-11-10 20:01:04.000 -08:00 mergetool-pr* f7e7de121e5d
| | Rename `jj resolve` to `jj conflict resolve`
| | o 2406d3e3d9e6 ilyagr@users.noreply.github.com 2022-11-24 19:45:46.000 -08:00 764188a78414
| | | write_all -> std::file::write
| o | c62dbc06da8b ilyagr@users.noreply.github.com 2022-10-30 01:23:45.000 -07:00 ilya* divergent 86ae33dc6966
| |/  Documentation for `jj resolve` and merge tool config
| o c47b7a983914 ilyagr@users.noreply.github.com 2022-10-30 19:41:19.000 -07:00 mergetool2* a3deb889060f
| | Mergetool config
| o f7987e8fdbad ilyagr@users.noreply.github.com 2022-10-30 19:41:19.000 -07:00 divergent 508216f4996b
| | Refactor errors
| o 10b33904c5db ilyagr@users.noreply.github.com 2022-10-27 20:30:44.000 -07:00 divergent 6ee36ff26b77
| : New `jj resolve` command uses an external merge tool to resolve conflicts
| : o db25140d31a8 martinvonz@google.com 2022-09-22 15:34:25.000 -07:00 918da280837d
| : | readme: remove now-unnecessary `--bin jj` argument to `cargo install`
| : o 90013bb15181 martinvonz@google.com 2022-09-22 11:32:16.000 -07:00 e48334d96e91
| :/  testing: don't have cargo install test tools
| o c4b869aa460d yuya@tcha.org 2022-09-22 18:29:06.000 +09:00 51cb4d901c32
|/  cli: abbreviate operation id embedded in warning/error messages
o cf23ae0cf4c1 martinvonz@google.com 2021-03-11 21:45:04.000 -08:00 HEAD@git f79874d612e5
~ view: let repo get current operation from OpHeadsStore and pass in
```

### PR DESCRIPTION
**Pull request by yuja**
Because the use of the change id is recommended, any operation should abort
if a valid change id happens to match a commit id. We still try the commit
id lookup first as the change id lookup is more costly.

Ambiguous change/commit id is reported as AmbiguousCommitIdPrefix for now.
Maybe we can merge AmbiguousCommit/ChangeIdPrefix errors into one?

Closes #799

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)

### CODE REVIEW

File: lib/src/revset.rs [hunk 1]
```diff
@@ -177,17 +184,24 @@ pub fn resolve_symbol(
...
-        if let Some(ids) = resolve_change_id(repo, symbol)? {
-            return Ok(ids);
+        // Try to resolve as a commit/change id.
+        match (
+            resolve_short_commit_id(repo, symbol)?,
+            resolve_change_id(repo, symbol)?,
+        ) {
+            // Likely a root_commit_id, but not limited to it.
+            (Some(ids1), Some(ids2)) if ids1 == ids2 => Ok(ids1),
+            // TODO: maybe unify Ambiguous*IdPrefix error variants?
```
Comment (martinvonz) [inline lib/src/revset.rs:200]: sounds good

**Review by martinvonz — APPROVED** [review]
