### PR TITLE
Switch to ignore crate for gitignore handling.

### LINKED ISSUE #3031: Support unignoring files/folders in .gitignore
## Description

jj seems to ignore `!` in `.gitignore`.

## Steps to Reproduce the Problem

I have not tested it extensively, but this is a common use case for demonstration:

```
mkdir test
touch test/unignore_me
echo -e 'test/*\n!test/unignore_me' > .gitignore
git init
jj init --git-repo=.
jj commit -m 'Init'
jj st # The working copy is clean
git status # Unversioned files: test/
```

Also tested with `test/**` in `.gitignore`.

If it really is a jj issue it might be crucial. (I am pretty new to jj and have not followed all discussions. But I did search for similar issues.)

## Expected Behavior

jj should add `test/unignore_me` in the initial revision -- like ‘pure’ git.

## Actual Behavior

jj ignores `test/unignore_me`.

## Specifications

- Platform: Linux 6.7, wayland 
- Version: jj 0.13.0-5450e6c9bae40b941b05942bdd78a88e1b9093a6

### LINKED ISSUE #3064: gitignore panic on directory names that contain curly braces
## Description

Initializing a jj repo from an existing git repo fails in gitignore related checks if directory file names contain curly braces.

## Steps to Reproduce the Problem

1. `git clone git@github.com:drivendata/cookiecutter-data-science.git`
2. Create a global `.gitignore` file containing `__pycache__`
3. `jj git init --git-repo=.`

`.jj` gets created, but subsequent jj commands, e.g. `jj log`, also lead to the panic.

## Expected Behavior

No thread panic

## Actual Behavior

This gets printed to terminal:

```
Done importing changes from the underlying Git repo.
thread '<unnamed>' panicked at lib\src\gitignore.rs:139:40:
called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    ^{{ cookiecutter.repo_name }}/(.*/)?__pycache__/.*
      ^
error: repetition quantifier expects a valid decimal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)
```

## Specifications

- Platform: Windows 10
- Version: jj 0.14.0

### PR DESCRIPTION
**Pull request by daehyeok**
This PR rebase and fix broken test cases from #2499
# Changed internal behavior.
 If path is ends with slash(/) consider it as a directory. All dir path is passed after calling [`to_internal_dir_string`](https://github.com/martinvonz/jj/blob/ce295f8bc2a30a7baaffea0b4ad9fd2707357522/lib/src/repo_path.rs#L277). So it might not a problem. (any file system allowed to create file with slash??)

# Changed test cases
 Here is some regressions with previous implements. See `gitignore.rs` test cases 

### test_gitignore_unusual_symbols

| before  | after | 
| ------------- | ------------- |
| `assert!(!matches(b"\\w\n", "w"));`  |  `assert!(matches(b"\\w\n", "w"));`  | 

### dangling \\
 ignore module throw `Glob { glob: Some("a b \\"), err: "dangling '\\'" }` error
| before  | after | 
| ------------- | ------------- |
| `assert!(matches(b"a b \\  \n", "a b  "));` |  `assert!(GitIgnoreFile::empty().chain("", b"a b \\  \n").is_err());` 
| `assert!(matches(b"\\\n", "\\"));` |  `assert!(GitIgnoreFile::empty().chain("", b"\\\n").is_err());`

### Ignore trail CRs at EOL is ignored 
| before  | after | 
| ------------- | ------------- |
|`assert!(matches(b"a\r\r\n", "a\r"));` |  `assert!(matches(b"a\r\r\n", "a"));` | 
     

 ### Backslaps on path consider as a divider on Windows
```rust
    #[test]
    #[cfg(not(target_os = "windows"))]
    fn teest_gitignore_backslash_path() {
        assert!(!matches(b"/foo/bar", "/foo\\bar"));
        assert!(!matches(b"/foo/bar", "/foo/bar\\"));

        assert!(!matches(b"/foo/bar/", "/foo\\bar/"));
        assert!(!matches(b"/foo/bar/", "/foo\\bar\\/"));

        // Invalid escapes are treated like literal backslashes
        assert!(!matches(b"\\w\n", "\\w"));
        assert!(matches(b"\\\\ \n", "\\ "));
        assert!(matches(b"\\\\\\ \n", "\\ "));
    }

    #[test]
    #[cfg(target_os = "windows")]
    /// ignore crate consider backslaes as a directory divider onln on Windows.
    fn teest_gitignore_backslash_path() {
        assert!(matches(b"/foo/bar", "/foo\\bar"));
        assert!(matches(b"/foo/bar", "/foo/bar\\"));

        assert!(matches(b"/foo/bar/", "/foo\\bar/"));
        assert!(matches(b"/foo/bar/", "/foo\\bar\\/"));

        assert!(matches(b"\\w\n", "\\w"));
        assert!(!matches(b"\\\\ \n", "\\ "));
        assert!(!matches(b"\\\\\\ \n", "\\ "));
    }
```
       
        

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

Closes #3064
Closes #3031
Closes #2499

### CODE REVIEW

**Comment by daehyeok** [comment]
oops window panic when match '\\`
```
 matches(b"\\\\ \n", "\\ ")
!matches(b"\\w\n", "\\w")
```

**Comment by arxanas** [comment]
With this commit it seems to be 60% faster to perform `jj status`??

```
$ hyperfine --parameter-list rev 'gitignore^,gitignore' --setup 'git checkout "{rev}" && cargo build --release' --warmup 1 './target/release/jj --repository ../gecko-dev status'

Benchmark 1: ./target/release/jj --repository ../gecko-dev status (rev = gitignore^)
  Time (mean ± σ):      4.469 s ±  0.049 s    [User: 5.162 s, System: 10.370 s]
  Range (min … max):    4.416 s …  4.575 s    10 runs
 
Benchmark 2: ./target/release/jj --repository ../gecko-dev status (rev = gitignore)
  Time (mean ± σ):      2.791 s ±  0.065 s    [User: 2.589 s, System: 10.640 s]
  Range (min … max):    2.695 s …  2.869 s    10 runs
 
Summary
  ./target/release/jj --repository ../gecko-dev status (rev = gitignore) ran
    1.60 ± 0.04 times faster than ./target/release/jj --repository ../gecko-dev status (rev = gitignore^)
```

fsmonitor isn't enabled:

```
$ jj --repository ../gecko-dev config get core.fsmonitor
Config error: configuration property "core.fsmonitor" not found
For help, see https://github.com/martinvonz/jj/blob/main/docs/config.md.
```

Status output seem to be the same:

```
$ git checkout gitignore && cargo run -- --repository ../gecko-dev status >status.after  
$ git checkout gitignore && cargo run -- --repository ../gecko-dev status >status.after  
$ diff status.before status.after  # no output
```

File: lib/src/gitignore.rs [hunk 1]
```diff
@@ -306,37 +208,63 @@ mod tests {
...
+
         // Invalid escapes are treated like literal backslashes
+        assert!(!matches(b"\\w\n", "\\w"));
+        assert!(matches(b"\\\\ \n", "\\ "));
+        assert!(matches(b"\\\\\\ \n", "\\ "));
+    }
+
+    #[test]
+    #[cfg(target_os = "windows")]
+    /// ignore crate consider backslaes as a directory divider onln on Windows.
```
Comment (arxanas) [inline lib/src/gitignore.rs:235]:
```suggestion
    /// ignore crate consider backslashes as a directory divider only on Windows.
````

Does this mean we also need to check for `\` at the end of a path on Windows, instead of only `/`?

File: lib/src/gitignore.rs [hunk 2]
```diff
@@ -14,189 +14,99 @@
...
+        let mut builder = gitignore::GitignoreBuilder::new(&path);
+        for (i, input_line) in input.split(|b| *b == b'\n').enumerate() {
+            let line =
+                std::str::from_utf8(input_line).map_err(|err| GitIgnoreError::InvalidUtf8 {
+                    path: PathBuf::from(&path),
+                    line_num_for_display: i + 1,
+                    line: String::from_utf8_lossy(input_line).to_string(),
+                    source: err,
+                })?;
+            // TODO: do we need to provide the `from` argument? Is it for providing
```
Comment (arxanas) [inline lib/src/gitignore.rs:69]:
```suggestion
            // FIXME: do we need to provide the `from` argument? Is it for providing
```

If we don't plan to resolve this in this PR, let's change it to `FIXME`.

**Comment by joyously** [comment]
> ```
> $ git checkout gitignore && cargo run -- --repository ../gecko-dev status >status.after  
> $ git checkout gitignore && cargo run -- --repository ../gecko-dev status >status.after  
> $ diff status.before status.after  # no output
> ```

Where did you create `status.before`?

**Comment by arxanas** [comment]
@joyously oops, I pasted the wrong line, updated. (I omitted all the `cargo` output in between lines so I was copying them in multiple steps.)

**Comment by martinvonz** [comment]
> With this commit it seems to be 60% faster to perform `jj status`??

Wow, that's a huge difference! I didn't even know that our currently gitignore implementation took a significant part of the `jj status` time on any repo.

File: lib/src/gitignore.rs (hunk 1 above)
Comment (daehyeok) [reply lib/src/gitignore.rs:235]: I don't think so. path already provided after [`to_internal_dir_string`](https://github.com/martinvonz/jj/blob/ce295f8bc2a30a7baaffea0b4ad9fd2707357522/lib/src/repo_path.rs#L277) calling. it doesn't check OS.
 ```rust
pub fn to_internal_dir_string(&self) -> String {
        if self.value.is_empty() {
            String::new()
        } else {
            [&self.value, "/"].concat()
        }
    }
```

File: lib/src/gitignore.rs [hunk 3]
```diff
@@ -14,189 +14,99 @@
...
+                std::str::from_utf8(input_line).map_err(|err| GitIgnoreError::InvalidUtf8 {
+                    path: PathBuf::from(&path),
+                    line_num_for_display: i + 1,
+                    line: String::from_utf8_lossy(input_line).to_string(),
+                    source: err,
+                })?;
+            // FIXME: do we need to provide the `from` argument? Is it for providing
+            // diagnostics or correctness?
+            builder.add_line(None, line)?;
         }
```
Comment (poliorcetics) [inline lib/src/gitignore.rs:72]: what happens if the `input` is something like `b"abc\r\ndef" ? It will split as `[b"abc\r", b"def"]`, which I don't think is what we want.

We can handle it with something like:

```rust
let input_line = input_line.strip_suffix(&[b'\r']).unwrap_or(input_line);
```

We have other reports of CRLF on windows being annoying so a test to ensure we don't break it would be a bonus too!

Comment (poliorcetics) [reply lib/src/gitignore.rs:72]: Ah forget it, I see tests handling it already, I missed them in the see of `\` 😓

**Review by poliorcetics — APPROVED** [review]

File: cli/src/cli_util.rs [hunk 4]
```diff
@@ -481,6 +481,12 @@ impl From<WorkingCopyStateError> for CommandError {
     }
 }
 
+impl From<GitIgnoreError> for CommandError {
+    fn from(err: GitIgnoreError) -> Self {
+        user_error(format!("Failed to process .gitignore: {err}"))
```
Comment (yuja) [inline cli/src/cli_util.rs:486]: nit: use `user_error_with_message()` instead

or maybe just `user_error(err)` since `GitIgnoreError` provides enough context.

File: lib/src/gitignore.rs [hunk 5]
```diff
@@ -14,189 +14,99 @@
...
-        self.regex.is_match(path)
-    }
+use std::{fs, io};
+
+use ignore::gitignore;
+use thiserror::Error;
+
+#[derive(Debug, Error)]
+pub enum GitIgnoreError {
+    #[error("failed to read ignore patterns from file {path}: {source}")]
```
Comment (yuja) [inline lib/src/gitignore.rs:26]: nit: capitalize "Failed", and remove `: {source}` (which will be printed by CLI.)

File: lib/src/gitignore.rs [hunk 6]
```diff
@@ -306,37 +211,64 @@ mod tests {
...
         // Invalid escapes are treated like literal backslashes
+        assert!(!matches(b"\\w\n", "\\w"));
+        assert!(matches(b"\\\\ \n", "\\ "));
+        assert!(matches(b"\\\\\\ \n", "\\ "));
+    }
+
+    #[test]
+    #[cfg(target_os = "windows")]
+    /// ignore crate consider backslashes as a directory divider only on
+    /// Windows.
```
Comment (martinvonz) [inline lib/src/gitignore.rs:239]: Do you know if git does the same? Otherwise this seems like a bug that we should report to the `ignore` crate (and maybe help them fix). It doesn't seem important enough to block this PR, though.

File: cli/src/cli_util.rs [hunk 7]
```diff
@@ -481,6 +481,12 @@ impl From<WorkingCopyStateError> for CommandError {
     }
 }
 
+impl From<GitIgnoreError> for CommandError {
+    fn from(err: GitIgnoreError) -> Self {
+        user_error_with_message("Failed to process .gitignore.", err)
```
Comment (martinvonz) [inline cli/src/cli_util.rs:486]: What do we do when this happens? What does Git do in the same cases? It seem like we shouldn't fail to snapshot the working copy. Maybe we should report a bug to the `insta` crate if that's what happens in some cases where Git doesn't report an error.

File: lib/src/gitignore.rs (hunk 6 above)
Comment (daehyeok) [reply lib/src/gitignore.rs:239]: yes. It looks git also working similarly.
 Mac
```shell
 ~/Downloads/temp ❯ echo /foo/bar > .gitignore
 ~/Downloads/temp ❯ git init .
Initialized empty Git repository in /Users/daehyeok/Downloads/temp/.git/
 ~/Downloads/temp ❯ git check-ignore foo
 ~/Downloads/temp ❯ git check-ignore foo/bar
foo/bar
 ~/Downloads/temp ❯ git check-ignore foo\bar
 ~/Downloads/temp ❯ git check-ignore foo\\bar
 ~/Downloads/temp ❯
```

same test on Windows PowerShell
```shell
PS C:\Users\daehyeok\Downloads\ignore> git check-ignore foo
PS C:\Users\daehyeok\Downloads\ignore> git check-ignore foo/bar
foo/bar
PS C:\Users\daehyeok\Downloads\ignore> git check-ignore foo\bar
"foo\\bar"
PS C:\Users\daehyeok\Downloads\ignore> git ignore foo\\bar
"foo\\\\bar"

```

File: cli/src/cli_util.rs (hunk 7 above)
Comment (daehyeok) [reply cli/src/cli_util.rs:486]: Actually it only come from non ignore crate code during parse path.
(chain and chain_with_file  function in `lib/src/gitignore.rs`
``` rust
pub fn chain(
        self: &Arc<GitIgnoreFile>,
        prefix: &str,
        input: &[u8],
    ) -> Result<Arc<GitIgnoreFile>, GitIgnoreError> {
        let path = self.path.clone() + prefix;
        let mut builder = gitignore::GitignoreBuilder::new(&path);
        for (i, input_line) in input.split(|b| *b == b'\n').enumerate() {
            let line =
                std::str::from_utf8(input_line).map_err(|err| GitIgnoreError::InvalidUtf8 {
                    path: PathBuf::from(&path),
                    line_num_for_display: i + 1,
                    line: String::from_utf8_lossy(input_line).to_string(),
                    source: err,
                })?;
```

```rust
pub fn chain_with_file(
        self: &Arc<GitIgnoreFile>,
        prefix: &str,
        file: PathBuf,
    ) -> Result<Arc<GitIgnoreFile>, GitIgnoreError> {
        if file.is_file() {
            let buf = fs::read(&file).map_err(|err| GitIgnoreError::ReadFile {
                path: file.clone(),
                source: err,
            })?;
```

File: lib/src/gitignore.rs (hunk 6 above)
Comment (martinvonz) [reply lib/src/gitignore.rs:239]: Ah, good. Thanks for checking! I checked the Git spec https://git-scm.com/docs/gitignore before asking and I didn't find anything there. I guess it's an undocumented feature. I'm happy the `ignore` crate matches the behavior.

File: cli/src/cli_util.rs (hunk 7 above)
Comment (martinvonz) [reply cli/src/cli_util.rs:486]: I see. Then I think we should change our code to avoid returning an error in this case. We would ideally match Git's behavior. Seems fine to attempt to read the entire file as utf8 and ignore it if that fails. Or check exactly what git does if you feel like it, but I'm not going to insist.

Comment (daehyeok) [reply cli/src/cli_util.rs:486]: Got it. I guess git just treat as a binary string.

```console
# create utf8 file.
daehyeok@macbook:~/temp$ echo "파일"  > "파일"
# Git status showing hex codes instead of utf8 string.
daehyeok@macbook:~/temp$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"\355\214\214\354\235\274"

nothing added to commit but untracked files present (use "git add" to track)
daehyeok@macbook:~/temp$
# Write utf8 path to gitginore
daehyeok@macbook:~/temp$ echo "파일"  > .gitignore
# Check it's work or not.
daehyeok@macbook:~/temp$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

nothing added to commit but untracked files present (use "git add" to track)
daehyeok@macbook:~/temp$
# Let's see what happen when gitignore contain non utf8(euckr)
daehyeok@macbook:~/temp$ iconv -f utf8 -t euc_kr 파일  > ./.gitignore
daehyeok@macbook:~/temp$ iconv -f utf8 -t euckr 파일 | xargs git check-ignore
"\306\304\300\317"
```

Comment (arxanas) [reply cli/src/cli_util.rs:486]: However, jj only allows UTF-8 paths, so we already can't do "what Git does"...

Unlike Git, if we fail to ignore something (if, upon encountering an incomprehensible pattern in a `.gitignore` file, we simply logged a warning and proceeded with snapshotting anyways), we run the risk of accidentally committing secrets or excessively-large files. For Git, it would be fine to log a warning and proceed, because the user still has to actively stage and commit changes to those files.

Comment (daehyeok) [reply cli/src/cli_util.rs:486]: >  we run the risk of accidentally committing secrets or excessively-large files. 

`chain` and `chain_with_file` only used to parse .gitignore file. so it will not change current JJ behavior. is it right?
 Warning/ignore then process might need to use JJ with legacy git repo.
 
 Also current version(0.14) already progressed with non utf8 gitignore.

Comment (daehyeok) [reply cli/src/cli_util.rs:486]: hmm How can I write warning log and progressed on `lib` codes?

Comment (martinvonz) [reply cli/src/cli_util.rs:486]: Good point that we should be careful to not commit files that were supposed to be ignored. So erroring out as you had done sounds good then, @daehyeok. I think that means this PR is ready to merge, right?

**Review by martinvonz — APPROVED** [review]

File: cli/src/cli_util.rs (hunk 7 above)
Comment (martinvonz) [reply cli/src/cli_util.rs:486]: > Also current version(0.14) already progressed with non utf8 gitignore.

Yes, that's correct, but maybe we shouldn't have done that, as @arxanas noted.

Comment (daehyeok) [reply cli/src/cli_util.rs:486]: > Good point that we should be careful to not commit files that were supposed to be ignored. So erroring out as you had done sounds good then, @daehyeok. I think that means this PR is ready to merge, right?

yes, it we don't have any other concern  :blush:
