### PR TITLE
Fix a bug when the target of `jj split` has merge commit children

### LINKED ISSUE #3483: Splitting a parent of a merge commit results in weird changes to the commit graph
## Steps to Reproduce the Problem

I'm very curious if others can reproduce this.

1. `jj git clone --colocate https://github.com/ilyagr/jj-bug` (Get a perfectly organized and orderly repo 🤣 )
1. `cd jj-bug`
1. `jj branch track 'glob:*@origin'`

Then:

```console
$ jj log -r ilya-
○  xpzxqz ilyagr@ 50 minutes ago conflictsides f503642
│  conflicts.rs: label conflict number and sides next to conflict markers
~

○  txsstw ilyagr@ 1 hour ago diffedit3 be2133e
│  diff editor: bundle a new `:builtin-web` GUI diff editor
~

○  nutytz ilyagr@ 1 hour ago gvimdiff 4a41932
│  merge_tools.toml: add gvimdiff config
~

○  ypqnrx ilyagr@ 1 hour ago verdate 3aded1d
│  cli version: Put `+` before build data instead of `-`
~
$ jj split -r conflictsides CHANGELOG.md  # Accept the descriptions as they are in the editor
Rebased 11 descendant commits
First part: xpzxqz 6cc476f conflicts.rs: label conflict number and sides next to conflict markers
Second part: tvootm 40d7ded conflictsides*| conflicts.rs: label conflict number and sides next to conflict markers
New conflicts appeared in these commits:
  trmunt 09a627e local-de3*| (conflict) Use local ../diffedit3-working
To resolve the conflicts, start by updating to it:
  jj new trmunttywktn
Then use `jj resolve`, or edit the conflict markers in the file directly.
Once the conflicts are resolved, you may want inspect the result with `jj diff`.
Then run `jj squash` to move the resolution into the conflicted commit.

$ jj log -r ilya-   # Changes weirdly
○  tvootm ilyagr@ 2 minutes ago conflictsides* 40d7ded
│  conflicts.rs: label conflict number and sides next to conflict markers
~
```

What happened to all the other parents of `ilya`?

## Specifications

- Platform: Mac OS
- Version: a few days old, customized: `jj 0.16.0+20240405-fd26902376c1dc96`

### PR DESCRIPTION
**Pull request by emesterhazy**
Ilya reported this in https://github.com/martinvonz/jj/issues/3483.

The bug was introduced in https://github.com/martinvonz/jj/commit/976320726d99659936eeab0e71b42d816dffbac0.

Before this fix, `jj split` dropped any parents what weren't involved in the split when it rebased the children of the commit being split. This meant that any children which were merge commits lost their other parents unintentionally.

Fixes #3483

### CODE REVIEW

File: cli/tests/test_split_command.rs [hunk 1]
```diff
@@ -377,3 +377,57 @@ JJ: Lines starting with "JJ: " (like this one) will be removed.
...
+    // Set up the editor and do the split.
+    let edit_script = test_env.set_up_fake_editor();
+    std::fs::write(
+        edit_script,
+        [
+            "dump editor1",
+            "write\nAdd file1",
+            "next invocation\n",
+            "dump editor2",
+            "write\nAdd file2",
```
Comment (martinvonz) [inline cli/tests/test_split_command.rs:414]: nit: are the "dump" instructions needed? we don't seem to inspect the dumped files, so i would think not

File: cli/src/commands/split.rs [hunk 2]
```diff
@@ -208,3 +201,34 @@ the operation will be aborted.
...
+    let children: Vec<Commit> = RevsetExpression::commit(original_commit.id().clone())
+        .children()
+        .evaluate_programmatic(tx.base_repo().as_ref())?
+        .iter()
+        .commits(tx.base_repo().store())
+        .try_collect()?;
+    let mut num_rebased = 0;
+    for child in children {
+        let mut new_parents = new_siblings.clone();
+        new_parents.extend(
```
[the remark this answers is not in the document]
Comment (martinvonz) [reply cli/src/commands/split.rs:223]: How about doing what @yuja suggested in https://github.com/martinvonz/jj/issues/3483#issuecomment-2049873942? That should be simpler, and arguably more consistent

File: cli/tests/test_split_command.rs (hunk 1 above)
Comment (emesterhazy) [reply cli/tests/test_split_command.rs:414]: You're right. I copied this from above but the dumps aren't needed in this case.

File: cli/src/commands/split.rs [hunk 3]
```diff
@@ -208,3 +201,34 @@ the operation will be aborted.
...
+            child
+                .parents()
+                .into_iter()
+                // Filter out the commit being split.
+                .filter(|c| c.id() != original_commit.id()),
+        );
```
Comment (martinvonz) [inline cli/src/commands/split.rs:229]: In order to preserve the parent order better, I think this should be using `flat_map()` where we replace the old parent by the new ones and leave unrelated parents unchanged.

File: cli/src/commands/split.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (martinvonz) [reply cli/src/commands/split.rs:223]: Makes sense. Let's simplify it later instead.

File: cli/src/commands/split.rs (hunk 3 above)
Comment (emesterhazy) [reply cli/src/commands/split.rs]: I thought about this issue when I wrote it but I didn't know about `flat_map`. This is great. Thanks!

File: cli/src/commands/split.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (emesterhazy) [reply cli/src/commands/split.rs]: I assume you're referring to the discussion about simplifying this after the rebase API refactor.

https://github.com/martinvonz/jj/issues/3483#issuecomment-2050006352

SGTM

File: cli/src/commands/split.rs [hunk 4]
```diff
@@ -208,3 +201,37 @@ the operation will be aborted.
...
+    let mut num_rebased = 0;
+    for child in children {
+        let new_parents = child
+            .parents()
+            .into_iter()
+            .flat_map(|c| {
+                if c.id() == original_commit.id() {
+                    new_siblings.clone().into_iter()
+                } else {
+                    vec![c].into_iter()
```
Comment (martinvonz) [inline cli/src/commands/split.rs:229]: nit: I think this is `std::iter::once(c)`

**Review by martinvonz — APPROVED** [review]
Thanks for the quick fix!

File: cli/src/commands/split.rs (hunk 4 above)
Comment (emesterhazy) [reply cli/src/commands/split.rs]: The types of the two iterators need to be the same, otherwise it won't compile. I suppose we could box two different types of iterators, but that also requires an explicit `-> Box<dyn Iterator<Item=Commit>>` on the lambda.

It turns out that the `into_iter()` calls aren't necessary though so I removed them.
