### PR TITLE
cli: add better error message when immutable_heads() cannot be resolved

### LINKED ISSUE #3415: Writes to repository fail if the configured immutable_heads can't be resolved.
## Steps to Reproduce the Problem

1.`jj git clone git@github.com:martinvonz/jj.git`
2. `cd jj`
3. `jj config set --repo "revset-aliases.immutable_heads()" "main@origin | gh-pages@origin"`
4. `jj git remote rename origin upstream`
5. `jj new`

## Expected Behavior
A new change is created or a clear error telling me how to resolve this issue is shown

## Actual Behavior
An unclear error is shown "Error: Revision "main@origin" doesn't exist"

## Specifications

- Platform: MacOS 14.4
- Version: 0.15.1

### PR DESCRIPTION
**Pull request by noahmayr**
Fixes #3415 

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

File: cli/src/cli_util.rs [hunk 1]
```diff
@@ -1012,7 +1012,25 @@ impl WorkspaceCommandHelper {
...
+                    name,
+                    candidates: _,
+                }) = e
+                else {
+                    return e.into();
+                };
+                user_error(format!(
+                    "The expression '{}' of immutable_heads() could not be resolved, if you \
+                     configured specific branch names consider wrapping them with 'present()' or \
+                     using the functions 'branches()' / 'remote_branches()'.",
```
Comment (PhilipMetzger) [inline cli/src/cli_util.rs:1028]: Use a raw string here (`r#"foo"#`) and inline the identifier.

**Review by PhilipMetzger — APPROVED** [review]
Just a minor nit else LG.

File: cli/src/cli_util.rs (hunk 1 above)
Comment (PhilipMetzger) [reply cli/src/cli_util.rs]: I meant 
```rust 
format!(r#""The expression '{name}' of immutable_heads() ..."#);
```

Comment (noahmayr) [reply cli/src/cli_util.rs]: wanted to ask what you meant by that but had to do something else, makes sense

File: docs/contributing.md [hunk 2]
```diff
@@ -114,7 +114,7 @@ You will probably also want to make the `gh-pages` branch immutable (and thereby
 hidden from the default `jj log` output) by running the following in your repo:
 
 ```shell
-jj config set --repo "revset-aliases.immutable_heads()" "main@origin | gh-pages@origin"
+jj config set --repo "revset-aliases.immutable_heads()" 'remote_branches(exact:"main") | remote_branches(exact:"origin")'
```
Comment (bnjmnt4n) [inline docs/contributing.md:117]: Should the second alternative be `gh-pages`?

Comment (noahmayr) [reply docs/contributing.md]: yeah, I seem to have copy pasted the wrong segment

File: cli/src/cli_util.rs [hunk 3]
```diff
@@ -1012,7 +1012,22 @@ impl WorkspaceCommandHelper {
...
+                    name,
+                    candidates: _,
+                }) = e
+                else {
+                    return e.into();
+                };
+                user_error_with_hint(format!(
+                    r#"The revision "{name}" used in immutable_heads() does not exist"#
+                ), r#"If you configured specific branch names consider wrapping them with "present()" or using the functions "branches()" / "remote_branches()"."#)
+            })?
```
Comment (martinvonz) [inline cli/src/cli_util.rs:1028]: Do you think it's time to extract the iterator to a variable?

```rust
let commit_id_iter = ...;
if let Some(commit_id) = commit_id_iter.next() {
  ...
}

```

Comment (martinvonz) [inline cli/src/cli_util.rs:1028]: I think early returns make sense if there's more code following, but here there's a single expression after it. I feel like this would be clearer using `match` or `if let`. Worth trying?

Comment (noahmayr) [reply cli/src/cli_util.rs]: I think that's more readable yeah

Comment (noahmayr) [reply cli/src/cli_util.rs]: Went with `match`, what do you think?

File: cli/src/cli_util.rs [hunk 4]
```diff
@@ -1012,7 +1012,20 @@ impl WorkspaceCommandHelper {
...
+        let mut commit_id_iter = match expression.evaluate_to_commit_ids() {
+            Ok(t) => Ok(t),
+            Err(UserRevsetEvaluationError::Resolution(RevsetResolutionError::NoSuchRevision {
+                name,
+                candidates: _,
+            })) => Err(user_error_with_hint(
+                format!(r#"The revision "{name}" used in immutable_heads() does not exist"#),
+                r#"If you configured specific branch names consider wrapping them with "present()" or using the functions "branches()" / "remote_branches()"."#,
+            )),
+            Err(e) => Err(e.into()),
```
Comment (martinvonz) [inline cli/src/cli_util.rs:1025]: Can the first case and this case be combined into `other => other?`?

**Review by martinvonz — APPROVED** [review]

File: cli/src/cli_util.rs (hunk 4 above)
Comment (noahmayr) [reply cli/src/cli_util.rs:1025]: I tried that, but since user_error(_with_hint) returns a `CommandError` I sadly have to call `e.into()` explicitly

Comment (martinvonz) [reply cli/src/cli_util.rs]: I see. I'm fine with either that or keeping it as is.

File: cli/src/cli_util.rs [hunk 5]
```diff
@@ -1012,7 +1012,19 @@ impl WorkspaceCommandHelper {
...
+        let mut commit_id_iter = match expression.evaluate_to_commit_ids() {
+            Err(UserRevsetEvaluationError::Resolution(RevsetResolutionError::NoSuchRevision {
+                name,
+                candidates: _,
+            })) => Err(user_error_with_hint(
+                format!(r#"The revision "{name}" used in immutable_heads() does not exist"#),
+                r#"If you configured specific branch names consider wrapping them with "present()" or using the functions "branches()" / "remote_branches()"."#,
+            )),
+            other => other.map_err(Into::into),
+        }?;
```
Comment (yuja) [inline cli/src/cli_util.rs:1025]: nit: perhaps, `config_error_with_message().hinted()` is more appropriate here.

And I personally think we don't need to explicitly check the error type. `NoSuchRevision` isn't the only error that the user could make.

Comment (martinvonz) [reply cli/src/cli_util.rs:1025]: Good point.

It would also be good to have a test or two in https://github.com/martinvonz/jj/blob/main/cli/tests/test_immutable_commits.rs

Comment (noahmayr) [reply cli/src/cli_util.rs:1025]: hmm, the hint in this case does depend on the specific type of error and to me it seems like `RevsetEvaluationError` and `RevsetResolutionError::StoreError` would not be config errors. 
It'd make sense for the other ones, but in that case I'd either drop the hint or only have that hint in case of that specific error.

Comment (yuja) [reply cli/src/cli_util.rs:1025]: > it seems like `RevsetEvaluationError` and `RevsetResolutionError::StoreError` would not be config errors.

It's technically correct that `StoreError` isn't a config error, but I think it's less likely to occur, and the user can see what happened if we provided the original error.

Regarding the hint, I prefer removing it. If the user configured a specific branch name with a specific remote, the resolution error shouldn't be suppressed by `present()`.

Comment (noahmayr) [reply cli/src/cli_util.rs]: Updated, will add some tests later

Comment (noahmayr) [reply cli/src/cli_util.rs]: Added some tests

File: cli/src/cli_util.rs [hunk 6]
```diff
@@ -1012,7 +1012,12 @@ impl WorkspaceCommandHelper {
         let immutable = revset_util::parse_immutable_expression(&self.revset_parse_context())?;
         let mut expression = self.attach_revset_evaluator(immutable)?;
         expression.intersect_with(&to_rewrite_revset);
-        if let Some(commit_id) = expression.evaluate_to_commit_ids()?.next() {
+
+        let mut commit_id_iter = expression.evaluate_to_commit_ids().map_err(|e| {
+            config_error_with_message("Invalid `revset-aliases.immutable_heads()`", e)
+        })?;
```
Comment (yuja) [inline cli/src/cli_util.rs:1018]: (Optional) can you also add a similar check to the `parse_*()` result?

**Review by yuja — APPROVED** [review]
Thanks!

File: cli/src/cli_util.rs (hunk 6 above)
Comment (noahmayr) [reply cli/src/cli_util.rs:1018]: Should I just do the whole chain then? (meaining also attach_revset_evaluator)

Comment (yuja) [reply cli/src/cli_util.rs:1018]: No we can't. They returns different error types, and `attach_revset_evaluator()` has its error context (= "revse.short-prefixes".)

Comment (noahmayr) [reply cli/src/cli_util.rs:974]: 👍🏻
