### PR TITLE
cli: add --allow-empty-description flag to push

### LINKED ISSUE #2633: Can't push changes to a repo that already has a change with an empty log message
## Description

I wanted to push a trivial cleanup change to a friend's project, but [this commit](https://github.com/zaphar/kitchen/commit/dcc574ca60a9) already deep in the history has no log message, and prevents me from pushing to my fork entirely.

## Steps to Reproduce the Problem

1. Make a change to an existing history that has a buried empty log message
1. Try to push

## Expected Behavior
The push isn't blocked because the outgoing set doesn't contain any empty log messages.

## Actual Behavior
Creating branch push-wsksktrvyzky for revision wsks
Error: Won't push commit dcc574ca60a9 since it has no description

## Specifications

- Platform: macOS 14.1.1, aarch64
- Version: martinvonz/jj@4f2503cbced88490e1b700e8a47d5a86e5153811

### PR DESCRIPTION
**Pull request by mgattozzi**
This commit adds an optional flag to be able to push commits with an empty description to a remote git repo. While the default behavior is ideal we might need to interact with a repo that has an empty commit description in it. I ran into this issue a few weeks ago pushing commits from an open source repo to an empty repo and had to go back to using git for that push as I would not want to rewrite the history which was many many years long just for that.

This flag allows users an escape hatch for pushing empty descriptions for commits and they're sure that they want that behavior.

This commit adds the flag to the `git push` command and updates the docs for the command. It also adds a new test to make sure that the flag works as intended alongside the old test which makes sure to reject an empty message for a commit.

Closes #2633

@martinvonz here's the PR I said I would drop by this week to fix my issue. Thanks for pointing things out. It was quite an easy PR to do and the codebase is well organized. I've also signed the CLA since this is the first time I'm contributing to the repo.

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [x] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

File: cli/tests/test_git_push.rs [hunk 1]
```diff
@@ -644,6 +644,23 @@ fn test_git_push_no_description() {
     "###);
 }
 
+#[test]
+fn test_git_allow_push_no_description() {
```
Comment (emesterhazy) [inline cli/tests/test_git_push.rs:648]: Personally, I think that it would be better to add a second push invocation to the existing `test_git_push_no_description` test so that it's clear that the error can be bypassed using the flag.

I don't think this needs to be a separate test.

File: cli/tests/cli-reference@.md.snap [hunk 2]
```diff
@@ -1,6 +1,5 @@
 ---
 source: cli/tests/test_generate_md_cli_help.rs
-description: "AUTO-GENERATED FILE, DO NOT EDIT. This cli reference is generated as an `insta` snapshot. MkDocs follows they symlink from docs/cli-reference.md to the snap. Unfortunately, `insta` unavoidably creates this header. Luckily, MkDocs ignores the header since it has the same format as Markdown headers. TODO: MkDocs may fail on Windows if symlinks are not enabled in the OS settings"
```
[the remark this answers is not in the document]
Comment (mgattozzi) [reply cli/tests/cli-reference@.md.snap:3]: I did, this must have been a stray write from when I looked at the file

File: cli/src/commands/git.rs [hunk 3]
```diff
@@ -220,6 +220,9 @@ pub struct GitPushArgs {
     /// correspond to missing local branches.
     #[arg(long)]
     deleted: bool,
+    /// Push branches that contain empty descriptions
```
[the remark this answers is not in the document]
Comment (mgattozzi) [reply cli/src/commands/git.rs:223]: yes it should be!

File: cli/tests/cli-reference@.md.snap (hunk 2 above)
[the remark this answers is not in the document]
Comment (mgattozzi) [reply cli/tests/cli-reference@.md.snap:3]: Hmmm I had added it back. I wonder if cargo insta did something. I'll manually put it back for now.

File: cli/src/commands/git.rs [hunk 4]
```diff
@@ -220,7 +220,7 @@ pub struct GitPushArgs {
     /// correspond to missing local branches.
     #[arg(long)]
     deleted: bool,
-    /// Push branches that contain empty descriptions
+    /// Push branches with commits that contain empty descriptions
```
Comment (martinvonz) [inline cli/src/commands/git.rs:223]: nit: squash this commit into the previous one (see https://martinvonz.github.io/jj/v0.17.1/contributing/#code-reviews)

Comment (mgattozzi) [reply cli/src/commands/git.rs:223]: Ah perfect. I prefer squashing and force pushing, but everyone is a bit different. I've squashed and pushed the changes! Let me know if you need anything else @martinvonz and I can take a look at it when I get the time.

File: cli/src/commands/git.rs [hunk 5]
```diff
@@ -220,6 +220,9 @@ pub struct GitPushArgs {
     /// correspond to missing local branches.
     #[arg(long)]
     deleted: bool,
+    /// Push branches with commits that contain empty descriptions
```
Comment (martinvonz) [inline cli/src/commands/git.rs:223]: It sounds a bit like this would find commits with empty descriptions and push them. Maybe it's clear enough with the `--allow` part of the flag name, but maybe it's still better to say "Allow pushing commits with empty description" or something like that? I don't think the "branches" in the description really helps either (which is why I didn't include it in my proposal).

**Review by thoughtpolice — COMMENTED** [review]
IMO, this also requires some kind of persistent configuration option, ~~because in practice you would basically have to add it 100% of the time you wanted to `jj git push` if your revision has an empty working copy as an ancestor in the repository; `nixpkgs` is an example of this (a completely empty commit snuck in a few months ago so now `jj git push` is FUBAR.)~~ EDIT: this was rather wrong, see my comment https://github.com/martinvonz/jj/pull/3653#issuecomment-2104867326 for the exact scenario I was thinking of. 

See https://github.com/martinvonz/jj/commit/db14f331703abbab7fc09255d5caa641077b43c4 for an example of how to add such an option; maybe `git.allow-empty-push = true` or something would be a good name.

**Comment by emesterhazy** [comment]
> IMO, this also requires some kind of persistent configuration option, because in practice you would basically have to add it 100% of the time you wanted to `jj git push` if your revision has an empty working copy as an ancestor in the repository; `nixpkgs` is an example of this (a completely empty commit snuck in a few months ago so now `jj git push` is FUBAR.)
> 
> See [db14f33](https://github.com/martinvonz/jj/commit/db14f331703abbab7fc09255d5caa641077b43c4) for an example of how to add such an option; maybe `git.allow-empty-push = true` or something would be a good name.

Ugh, good point. But if that's the case then we really should have a way to only allow pushing immutable empty commits. Otherwise once the repo is poisoned it's easy to accidentally push more empty commits, right?

**Comment by martinvonz** [comment]
> IMO, this also requires some kind of persistent configuration option, because in practice you would basically have to add it 100% of the time you wanted to `jj git push` if your revision has an empty working copy as an ancestor in the repository;

Is that really true? We only check the commits that are not already on the server (according to our records), right?

**Comment by thoughtpolice** [comment]
> > IMO, this also requires some kind of persistent configuration option, because in practice you would basically have to add it 100% of the time you wanted to `jj git push` if your revision has an empty working copy as an ancestor in the repository;
> 
> Is that really true? We only check the commits that are not already on the server (according to our records), right?

Ah, I think you're right. I managed to recreate the scenario in question. Basically, if you:

- Have a `master@origin` that has an empty commit merged in is history
- Then you have a fork `master@gh` (your GH fork) that you want to push to,
- But the fork does *not* have that empty commit in its history, because it is older/lagging,
- `jj git push` fails, because you try to push an empty commit

So, in this case it's because the remote fork was lagging a bit; I hadn't updated it in a few months. Thanks for double checking me. However, it's a bit of a strange edge case. But maybe my earlier statement still applies about adding a config option. Not as hard of a requirement though, since using `--ignore-empty-description` in a once-off way can solve that problem.

**Comment by martinvonz** [comment]
> But maybe my earlier statement still applies about adding a config option.

IMO, let's start with the flag and then add a config option later if we hear that it's somewhat common that people want to always pass the flag (perhaps because they push to their own private repo where they're okay with missing descriptions).

File: cli/src/commands/git.rs (hunk 5 above)
Comment (emesterhazy) [reply cli/src/commands/git.rs:223]: Yeah, I agree that adding "allow" is a good idea. I wasn't sure about the terminology, but I think referring to commits instead of branches might be better.

Something like "Allow pushing commits with empty descriptions."

**Review by emesterhazy — COMMENTED** [review]
This looks pretty good to me but I'll let someone else approve since I'm traveling and don't have access to a computer right now.

**Comment by ilyagr** [comment]
I renamed the PR since it seems people agreed on `--allow-empty-description` (which is also my preference over `--ignore...`)

File: CHANGELOG.md
Comment (ilyagr) [inline CHANGELOG.md:1]: Please change the commit title to match the new option name.

**Comment by mgattozzi** [comment]
I've updated the PR with the proper description, changes to the flag docs, and dealt with the CHANGELOG conflict as well. I think this should be good to go.

**Review by yuja — APPROVED** [review]
lgtm, thanks.

**Comment by mgattozzi** [comment]
Updated again with the changelog and everything marked resolved. Just needs someone to merge it.

**Comment by emesterhazy** [comment]
LGTM. I'll merge this now then since Yuya also approved.
