### PR TITLE
Fix empty files can't be selected in builtin diff editor

### LINKED ISSUE #3016: Empty files in jj split
## Description
Empty files can not be split out of the current commit

## Steps to Reproduce the Problem

1. touch jj-is-the-best
2. `jj split`
3. `jj-is-the-best` is not selectable.

## Expected Behavior

Empty files should be able to be selected

## Actual Behavior

Empty files can not be selected

## Specifications
- Platform: Linux
- Version: `jj 0.14.0`

### PR DESCRIPTION
**Pull request by emesterhazy**
This fixes several issues that made working with empty files difficult using the builtin diff editor.

1. The scm-record library used for the editor expects each file to have at least one section. For empty files this should be a file mode section. jj wasn't rendering this mode section, which prevented empty files from being selected at all.

2. The scm-record library returns `SelectedContents::Absent` if the file has no contents after the diff editor is invoked. This can be because of several reasons: 1) the file is new and empty; 2) the file was empty before and is still empty; 3) the file has been deleted. Perhaps this is a bug in scm-record and it should return `SelectedContents::Unchanged` or `SelectedContents::Present` if the file hasn't been deleted. Until this is patched upstream, we can work around it by disambiguating these cases.

See https://github.com/arxanas/scm-record/issues/26 for the upstream bug.

Fixes #3016

### CODE REVIEW

File: cli/src/merge_tools/builtin.rs [hunk 1]
```diff
@@ -56,6 +56,21 @@ enum FileContents {
...
+            // Being absent is different from being present and empty.
+            FileContents::Absent => false,
+            FileContents::Text {
+                contents: _,
+                hash: _,
+                num_bytes,
+            } => *num_bytes == 0,
+            FileContents::Binary { hash: _, num_bytes } => *num_bytes == 0,
+        }
+    }
```
Comment (yuja) [inline cli/src/merge_tools/builtin.rs:71]: Maybe this can be inlined to caller? It's unclear why absent file isn't empty.

If I understand it, the condition to render the mode section is one side is `Absent` and the other side is `Text { num_bytes: 0 }`. If there were an empty binary file, I think the entry would be selectable.

Oh, btw, the binary section could be abused to render absent<->empty diff, but I'm not sure if it works and if it provides better UX.

File: cli/src/merge_tools/builtin.rs [hunk 2]
```diff
@@ -245,29 +278,36 @@ pub fn make_diff_files(
...
+                },
+            ) => {}
+            (
+                FileContents::Text {
+                    contents: _,
+                    hash: _,
+                    num_bytes: 0,
+                },
+                FileContents::Absent,
+            ) => {}
```
Comment (yuja) [inline cli/src/merge_tools/builtin.rs:310]: nit: maybe this is also a workaround for the upstream bug? add short comment about that?

**Review by yuja — COMMENTED** [review]
LGTM, but @arxanas might have better suggestion.

File: cli/src/merge_tools/builtin.rs (hunk 1 above)
Comment (emesterhazy) [reply cli/src/merge_tools/builtin.rs:71]: Good point about an empty binary file being selectable. I haven't tried it but I suspect you're right. I used the mode section because arxanas [mentioned on the bug](https://github.com/martinvonz/jj/issues/3016#issuecomment-1937857687) that new files should show a mode change. Rendering them as 0-byte binary files could work as well though.

It's not totally clear what `Absent` means, but it seems that it should mean that the file doesn't exist at all, otherwise it's hard to reason about whether a file exists or not after the user selects the changes they want.

File: cli/src/merge_tools/builtin.rs (hunk 2 above)
Comment (emesterhazy) [reply cli/src/merge_tools/builtin.rs:310]: I don't see this as a workaround necessarily. In this context `FileContents::Absent` means that the file doesn't exist. If the file exists on one side and is empty on the other then we'll render a mode change section. This matcher is to avoid also rendering an empty text lines section that just clutters up the UI.

This probably deserves an inline comment though. I'll add one.

File: cli/src/merge_tools/builtin.rs (hunk 1 above)
Comment (yuja) [reply cli/src/merge_tools/builtin.rs:71]: If we keep `is_empty()` function, I slight prefer making it return `Option<bool>`, and match `(None, Some(true))` pair.

I totally agree with the `Absent` definition.

Comment (emesterhazy) [reply cli/src/merge_tools/builtin.rs:85]: Ok I changed the return value to `Option<bool>` and moved the function to the `FileInfo` struct. I also added a `debug_assert!` to ensure that if the mode is absent the contents are also absent.

File: cli/src/merge_tools/builtin.rs [hunk 3]
```diff
@@ -237,6 +258,29 @@ fn make_diff_sections(
...
+        // The file is absent on one side. If it's empty on the other side, then
+        // a content diff section won't be added later. If we don't add the mode
+        // section now, then the file won't be selectable at all. If the file
+        // isn't empty, then we don't need to add a mode section since the user
+        // can select the contents instead and the mode change is implied.
+        // See https://github.com/martinvonz/jj/issues/3016.
+        return matches!(
+            (left.is_empty(), right.is_empty()),
+            (Some(true), None) | (None, Some(true))
+        );
```
Comment (yuja) [inline cli/src/merge_tools/builtin.rs:279]: nit: I would combine this and `.file_mode` comparison as follows, but I'm not sure which one is more readable. To me, the special case is one side is absent and the other side is not empty.
```rust
match (left.is_empty(), right.is_empty()) {
    (Some(false), None) | (None, Some(false)) => false,
    _ => left.file_mode != right.file_mode,
}
```

**Review by yuja — APPROVED** [review]
Thanks. There are no other comments, so I went ahead and flagged as approved.

File: cli/src/merge_tools/builtin.rs (hunk 3 above)
Comment (emesterhazy) [reply cli/src/merge_tools/builtin.rs]: Done. I like that this is much more concise, and I think it's just as understandable alongside a comment.

File: cli/src/merge_tools/builtin.rs (hunk 1 above)
Comment (arxanas) [reply cli/src/merge_tools/builtin.rs:85]: > I used the mode section because arxanas mentioned on the bug that new files should show a mode change. Rendering them as 0-byte binary files could work as well though.

comment(non-blocking): I think using either is justified. I was thinking of the mode change because I think that's how Git renders newly-added files with no contents (well, it probably *always* renders modes in diffs, but it's usually not notable except when there are other changes as well).

File: cli/src/merge_tools/builtin.rs [hunk 4]
```diff
@@ -64,6 +64,27 @@ pub struct FileInfo {
...
+    // Returns `Some(true)` if the file exists and is empty.
+    // Returns `None` if the file is absent and does not exist.
+    fn is_empty(&self) -> Option<bool> {
+        if let FileContents::Absent = self.contents {
+            // If the contents are absent the mode should be absent as well.
+            debug_assert!(self.file_mode == scm_record::FileMode::absent())
+        }
+        match self.contents {
+            // Being absent is different from being present and empty.
+            FileContents::Absent => None,
```
Comment (arxanas) [inline cli/src/merge_tools/builtin.rs:77]:
```suggestion
            FileContents::Absent => {
                // If the contents are absent the mode should be absent as well.
                debug_assert!(self.file_mode == scm_record::FileMode::absent());
                None
            }
```

suggestion: Inline the assertion here?

File: cli/src/merge_tools/builtin.rs [hunk 5]
```diff
@@ -380,7 +423,33 @@ pub fn apply_diff_builtin(
...
+                // TODO(https://github.com/arxanas/scm-record/issues/26): This
+                // is probably an upstream bug in scm-record. If the file exists
+                // but is empty, `get_selected_contents` should probably return
+                // `Unchanged` or `Present`. When this is fixed upstream we can
+                // simplify this logic.
+
+                // Currently, `Absent` means the file is either empty or
+                // deleted. We need to disambiguate three cases:
+                // 1. The file is new and empty.
+                // 2. The file existed before, is empty, and nothing changed.
```
Comment (arxanas) [inline cli/src/merge_tools/builtin.rs:435]: comment (non-blocking): I imagine that we shouldn't/don't generate any files for the UI in case 2, when the file hasn't changed?

**Review by arxanas — APPROVED** [review]
Thanks for fixing!

File: cli/src/merge_tools/builtin.rs (hunk 4 above)
Comment (emesterhazy) [reply cli/src/merge_tools/builtin.rs:77]: Good point, thanks!

File: cli/src/merge_tools/builtin.rs (hunk 5 above)
Comment (emesterhazy) [reply cli/src/merge_tools/builtin.rs:435]: I think what I mean here is that the user didn't select any changes, therefore the file won't have changed in the resulting tree. I _think_ that after the upstream changes the three cases will be mapped like this:

1. The file is new and empty => `Present("")`
2. The file existed before, is empty, and nothing changed => `Unchanged`
3. The file does not exist (it's been deleted) => `Absent`

I'm working on a patch for the upstream UI and will probably change `get_selected_contents` so that it behaves this way and disambiguates these cases. Assuming that gets merged we can update the dep for `jj` and clean up this `Absent` block :)

**Comment by emesterhazy** [comment]
Thanks for reviewing @arxanas!

**Comment by emesterhazy** [comment]
I'm going to submit this now and work on a patch for `scm-record` upstream. Once that's done I'll open another PR to clean incorporate the upstream changes.

**Comment by martinvonz** [comment]
Sounds good. Thanks, both of you!
