### PR TITLE
working_copy: don't visit whole ignored tree even if last in order

### LINKED ISSUE #247: Slow `jj status` with large numbers of ignored files
## Description

`jj status` is taking a while. I'm running it in https://github.com/arxanas/git-branchless, which is not a large repository:

```
$ git ls-files | wc -l
     116

$ git rev-list HEAD --count
816
```

Is there a way to profile this?

## Steps to Reproduce the Problem

1. `jj status`
2. It takes too long.

## Expected Behavior

`jj status` completes in <100ms after first invocation/warming up any caches.

## Actual Behavior

```
$ /usr/bin/time git status
On branch git
nothing to commit, working tree clean
        0.01 real         0.00 user         0.00 sys

$ /usr/bin/time jj status 
Parent commit: 98d9e3d77b9d cleanup: remove deprecated `git.io` link
Working copy : 6473a320cc51 
These branches have conflicts:
  merge
  move-individual-commits
  Use `jj branches` to see details. Use `jj branch <name> -r <rev>` to resolve.
The working copy is clean
        2.71 real         1.16 user         1.53 sys
```

I know that ahead/behind calculations can be slow; not sure if that's a factor here in detecting conflicted branches.

## Specifications

- Platform: macOS 11.6.5
- Version: jj @ 4a1576c87491ba732220dd783fb01c2cf075e8d4

### PR DESCRIPTION
**Pull request by martinvonz**
When committing the working copy, we try to not visit ignored
directories (as e.g. `target/` often is), but we need to visit it if
there are already tracked files in it. I initially missed that in
c1060610bda2 and then fixed it in a028f33e3b21. The fix works by
checking if the next path after the ignored path is inside the ignore
path (viewed as a directory). However, I forgot to handle the case
where there are no paths at all after the ignored path. So, for
example, if the `target/` directory should be ignored and it there
were no tracked paths after `target/` in alphabetical order, we would
still visit the directory. That's why the bug reproduced in the
`git-branchless` repo but not in the `jj` repo (because there are
files under `testing/` and `tests/` here).

Closes #247.

# Checklist

- [x] I have made relevant updates to `CHANGELOG.md`

### CODE REVIEW

File: lib/src/working_copy.rs [hunk 1]
```diff
@@ -391,6 +382,24 @@ impl TreeState {
         self.tree_id.clone()
     }
 
+    fn has_files_under(&self, dir: &RepoPath) -> bool {
+        // TODO: This is pretty ugly... Also, we should
+        // optimize it to check exactly the already-tracked files (we know that
+        // we won't have to consider new files in the directory).
+        let first_file_in_dir = dir.join(&RepoPathComponent::from("\0"));
+        if let Some((subdir_file, _)) = self
```
Comment (arxanas) [inline lib/src/working_copy.rs:390]: Maybe better now as a `match`?

**Review by arxanas — APPROVED** [review]
Heh, what a bug!
