### PR TITLE
squash doc: --keep-emptied let the description unchanged

### LINKED ISSUE #4473: `jj squash --keep-emptied` does not copy the description of the source commit
## Description

`jj squash` help page says that the description of the source commit, if any, will be copied or merged into the target commit description. This is not the case when using `--keep-emptied`.

## Steps to Reproduce the Problem

```
$ jj new
$ jj new -m "Some description"
$ echo foo > bar
$ jj squash --keep-emptied
$ jj log -r @-::
@  rtnywryn sam@rfc1149.net 2024-09-15 14:36:12 84bf696b
│  (empty) Some description
○  nsknwpvm sam@rfc1149.net 2024-09-15 14:36:12 5c65418c
│  (no description set)
```

## Expected Behavior

The description should have been moved to the target commit.

## Actual Behavior

No description copying or merging takes place.

## Specifications

- Platform: Linux
- Version: main

### PR DESCRIPTION
**Pull request by samueltardieu**
Fix #4473

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by samueltardieu** [comment]
Technically, each "change" would keep its own description, not each "commit". However, using "changes" instead of "commits" here would be confusing (even if technically more accurate) because the text talks about the "changes" (as in "diffs") present in the initial commits.

**Review by matts1 — APPROVED** [review]

File: cli/src/commands/squash.rs [hunk 1]
```diff
@@ -50,7 +50,8 @@ use crate::ui::Ui;
 ///
 /// If the source became empty and both the source and destination had a
 /// non-empty description, you will be asked for the combined description. If
-/// either was empty, then the other one will be used.
+/// either was empty, then the other one will be used. As an exception, when
+/// `--keep-emptied` is used, each commit keeps its own description.
```
Comment (martinvonz) [inline cli/src/commands/squash.rs:54]: An alternative solution is to update the paragraph with "If the source became empty" -> "If the source was abandoned" (or perhaps "If the source was abandoned (because it became empty and `--keep-emptied` was not requested)"). Thoughts?

Comment (matts1) [reply cli/src/commands/squash.rs:54]: I like that phrasing, I think it's much clearer since there's no special-casing.

Comment (samueltardieu) [reply cli/src/commands/squash.rs]: Agreed.
