### PR TITLE
git: propagate errors for missing commits when importing refs

### LINKED ISSUE #2022: BUG: "no match for id" panic when initializing repo with a bad object
## Description

When I run `jj init` in a github repo, I get this panic:

```
$ jj init --git-repo=.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ObjectNotFound { object_type: "commit", hash: "a430c04e28fbc783f99abbc701aaef35dd103803", source: Error { code: -3, klass: 9, message: "object not found - no match for id (a430c04e28fbc783f99abbc701aaef35dd103803)" } }', lib/src/git.rs:199:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
## Steps to Reproduce the Problem

I think this is happening because my repo has a bad object in it for some reason:

```
$ git show a430c04e28fbc783f99abbc701aaef35dd103803
fatal: bad object a430c04e28fbc783f99abbc701aaef35dd103803
```

I don't know how to create a git repo with a "bad object" but I expect that `jj init` might fail on another such repo.

## Expected Behavior

I've been using this git repo with no problems for years (I had no idea it had a bad object in it) and it would be nice to be able to use `jj` on it, though I don't know what the implications of that are -- maybe it's too dangerous.

An error message instead of a panic would definitely be an improvement.

## Specifications

- Platform: Mac OS
- Version: `jj 0.8.0-e7e49527efdfddf3eb29ce21e79b056c71c873d6`

### PR DESCRIPTION
**Pull request by martinvonz**
Closes #2022.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

File: lib/src/git.rs [hunk 1]
```diff
@@ -25,16 +25,20 @@ use itertools::Itertools;
...
 use crate::settings::GitSettings;
 use crate::view::{RefName, View};
 
-#[derive(Error, Debug, PartialEq)]
+#[derive(Error, Debug)]
 pub enum GitImportError {
+    #[error("Failed to read Git HEAD target commit {id}: {err}", id=id.hex())]
+    MissingHeadTarget { id: CommitId, err: BackendError },
+    #[error("Ancestor of Git ref {ref_name} is missing: {err}")]
+    MissingRefAncestor { ref_name: String, err: BackendError },
```
Comment (yuja) [inline lib/src/git.rs:41]: nit: add `#[source]` to these `err`s?

File: lib/src/git.rs [hunk 2]
```diff
@@ -208,13 +217,18 @@ pub fn import_some_refs(
...
+        for id in new_git_target.added_ids() {
+            prevent_gc(git_repo, id)?;
+            let commit =
+                store
+                    .get_commit(id)
+                    .map_err(|err| GitImportError::MissingRefAncestor {
+                        ref_name: ref_name.to_string(),
+                        err,
+                    })?;
+            mut_repo.add_head(&commit);
```
Comment (yuja) [inline lib/src/git.rs:230]: Better to `get_commit(id)` first? I think `prevent_gc()` would also fail if `id` was missing.

**Review by yuja — APPROVED** [review]

File: lib/src/git.rs (hunk 2 above)
Comment (martinvonz) [reply lib/src/git.rs:238]: Ah, that's better. Thanks!
