### PR TITLE
cli: error when `jj rebase -b` is used without `--destination`

### LINKED ISSUE #4770: `jj rebase --after main` causes thread panic
## Description
When using `jj rebase` with no `-r` -`s` or -`b` argument, I believe the default behaviour is the same as `jj rebase -b @ <args>`. 

It seems that `--after` is not a valid argument to combine with `-b`, but the cli does not properly display a friendly error in the "implicit" case.

## Steps to Reproduce the Problem

1. Run `jj rebase --after <revision>` in a jj repository.

## Expected Behavior
Displaying the same error as explicitly running `jj rebase -b @ --after main`:

```error: the argument '--branch <BRANCH>' cannot be used with '--insert-after <INSERT_AFTER>'```

## Actual Behavior
```
❯ jj rebase --after main

thread 'main' panicked at cli/src/commands/rebase.rs:274:14:
clap should enforce -d when used with -b
```

Output from running with **RUST_BACKTRACE=full**:

```
stack backtrace:
   0:        0x1031d2e74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x1031f4b1c - core::fmt::write::heedef092c8c0962e
   2:        0x1031cdff8 - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x1031d2ccc - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x1031d48bc - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x1031d45b0 - std::panicking::default_hook::h24535936bc1f51de
   6:        0x1031d5174 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   7:        0x1031d4ba4 - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   8:        0x1031d32fc - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
   9:        0x1031d4914 - _rust_begin_unwind
  10:        0x103248150 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  11:        0x1031f2744 - core::panicking::panic_display::hf23c98a61b03dc30
  12:        0x103248124 - core::option::expect_failed::hd7f592634f4db1af
  13:        0x102a93268 - jj_cli::commands::rebase::cmd_rebase::h22f4bf097df4c29c
  14:        0x102abedd4 - jj_cli::commands::run_command::h9b85c15c858d0dc4
  15:        0x10291fc14 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hac56075794e9a253
  16:        0x102a29b74 - jj_cli::cli_util::CliRunner::run::h174009057440dd27
  17:        0x10281e404 - jj::main::hedfc4096854b2cbc
  18:        0x10281e384 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8e2c448e74e53942
  19:        0x10281e39c - std::rt::lang_start::{{closure}}::h58b1bf8200ea7633
  20:        0x1031c5dfc - std::rt::lang_start_internal::hecc68fef83c8f44d
  21:        0x10281e448 - _main
```

## Specifications

- Platform: macOS
- Version: jj 0.22.0-1d7aaa6f8d8db233e25fa4a3627506f280a8c2ea

Specifically the `openSSH` fork by **bnjmnt4n**

### PR DESCRIPTION
**Pull request by bnjmnt4n**
Closes #4770.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [X] I have added tests to cover my changes

### CODE REVIEW

File: cli/src/commands/rebase.rs [hunk 1]
```diff
@@ -268,11 +268,12 @@ pub(crate) fn cmd_rebase(
...
         )?;
     } else {
-        let destination = args
-            .destination
-            .destination
-            .as_ref()
-            .expect("clap should enforce -d when used with -b");
+        let Some(destination) = args.destination.destination.as_ref() else {
+            return Err(cli_error(
+                "jj rebase without `-r`, `-s`, or `-b` requires the `--destination <DESTINATION>` \
```
Comment (yuja) [inline cli/src/commands/rebase.rs:273]: nit: `--destination` is required even if `-b` is explicitly specified. Maybe we can say "--destination is required to rebase a whole branch" or "--insert-before/after is not supported when rebasing a whole branch"?

We can also remove `conflicts_with` from `--branch`.

**Review by yuja — APPROVED** [review]
Thanks!
